### ISSUE TITLE
images

### ISSUE THREAD

**Issue by xinthink** [xinthink/react-native-material-kit#1]
![buttons](https://cloud.githubusercontent.com/assets/390805/8454632/a65ec8ae-2031-11e5-93ba-f95874aa3fa3.gif)

**Comment by xinthink** [comment]
![textfields](https://cloud.githubusercontent.com/assets/390805/8715858/2f420854-2bbb-11e5-8ec9-9ff35b6fdeed.gif)

**Comment by xinthink** [comment]
[Material Design Lite](http://www.getmdl.io/components/index.html#buttons-section) pre-defined buttons
![buttons-mdl](https://cloud.githubusercontent.com/assets/390805/8761525/08593298-2d88-11e5-98dc-6180a5122b1f.gif)

**Comment by xinthink** [comment]
[Material Design Lite](http://www.getmdl.io/components/#textfields-section) pre-defined textfields
![textfields-mdl](https://cloud.githubusercontent.com/assets/390805/8770805/a00a853e-2eea-11e5-9801-4fc96ddb6e62.gif)

**Comment by xinthink** [comment]
Material Design Lite [Icon Toggle](http://ww.getmdl.io/components/index.html#toggles-section/icon-toggle) & [Switch](http://ww.getmdl.io/components/index.html#toggles-section/switch)
![toggles-mdl](https://cloud.githubusercontent.com/assets/390805/8901336/a2a28c48-347a-11e5-9210-e93379fd36db.gif)

**Comment by xinthink** [comment]
Switches written in pure jsx
![js-switch-mdl](https://cloud.githubusercontent.com/assets/390805/9008325/08aa3776-37cc-11e5-825b-298585917055.gif)

**Comment by xinthink** [comment]
jsx textfields
![js-textfield-mdl](https://cloud.githubusercontent.com/assets/390805/9085678/8280484a-3bb1-11e5-9354-a244b0520736.gif)

**Comment by xinthink** [comment]
![progress-mdl](https://cloud.githubusercontent.com/assets/390805/9288698/01e31432-4387-11e5-98e5-85b18471baeb.gif)
![spinner-mdl](https://cloud.githubusercontent.com/assets/390805/9288699/01e3573a-4387-11e5-8f7b-6c34066846fe.gif)

**Comment by xinthink** [comment]
jsx slider
![js-slider-mdl](https://cloud.githubusercontent.com/assets/390805/9685661/44260e64-5352-11e5-9fea-0a8aecc07de2.gif)

**Comment by xinthink** [comment]
jsx sliders work on both iOS and Android
 ![js-slider-mdl](https://cloud.githubusercontent.com/assets/390805/10123318/6c502e6e-6569-11e5-924a-62c8b850511c.gif)

**Comment by xinthink** [comment]
![2015-10-03 7 44 23](https://cloud.githubusercontent.com/assets/390805/10262736/4411994a-6a07-11e5-8a72-b7a46ba5e4a9.png)

**Comment by xinthink** [comment]
spinner animation sucks on Android

Android 5.1
![js-spinner-android-5](https://cloud.githubusercontent.com/assets/390805/10303891/4af002bc-6c49-11e5-91b2-fa357c0c44d5.gif)

Even worse on Android 4
![js-spinner-android-4](https://cloud.githubusercontent.com/assets/390805/10303922/70d98624-6c49-11e5-9d6d-3ea20aca4919.gif)

**Comment by xinthink** [comment]
MDL Radio Buttons
![js-radio-mdl](https://cloud.githubusercontent.com/assets/390805/10442805/bdb08bc0-7188-11e5-8565-4ee0049ad590.gif)

**Comment by xinthink** [comment]
MDL Checkbox
![mdl-checkbox](https://cloud.githubusercontent.com/assets/390805/12009445/0f938cee-acb2-11e5-9732-434382f6cd84.gif)

**Comment by zichaolim** [comment]
You're Genius!

**Comment by xinthink** [comment]
JetBrains logo
![logo_jetbrains_1](https://cloud.githubusercontent.com/assets/390805/23090615/982de3f0-f5dc-11e6-92e1-a08f59f1065b.png)
