### ISSUE TITLE
Setting fillColor of Checkbox component but color does not change

### ISSUE THREAD

**Issue by leandrost** [xinthink/react-native-material-kit#104]
I am trying set the fillColor prop and the component still using Indigo color.

```js
 <MKCheckbox checked={true} fillColor="#f00" />
```
I tried setTheme too like the doc suggest but the result was the same.
I think that could be something with TickView widget but its just a guess.

**Comment by chinciusan** [comment]
I get this one too, only on iOS.

**Comment by leandrost** [comment]
By the way, i'm using android.

**Comment by xinthink** [comment]
Please update to RN 0.20.0 (the final release https://github.com/facebook/react-native/commit/6496feb61e9205baa3f25cf448c4fce912bd6250).
Android should work, iOS do have the problem, maybe caused by some change in RN 0.20.0

<img width="1099" alt="2016-02-21 11 30 26" src="https://cloud.githubusercontent.com/assets/390805/13200709/fb686b46-d88e-11e5-88c2-e94f40fdbf0d.png">

**Comment by braunsquared** [comment]
I'm having the same issue on iOS.  I did some quick digging and it seems the settings inside TickView.m are never being called.  This is true both for fillColor and insets.  I can see the conversion happen in RCTConvert for the color value I'm passing in, but then it's never set on the returned view.  I'm thinking this is most likely a bug related to 0.20 as it doesn't seem to happen on another project I have with 0.18.

**Comment by npomfret** [comment]
I've got the same issue (with RN 0.20.0) with IOS, the fill colour seems to be getting ignored.

**Comment by dionysiusmarquis** [comment]
+1

**Comment by kelvinaliyanto** [comment]
:+1:

**Comment by kelvinaliyanto** [comment]
+1

**Comment by adrienthiery** [comment]
Same issue on RN 0.21, on iOs only also.

I suspect it comes from the [re-implementation of processColor](https://github.com/facebook/react-native/commit/c8a0a3eff6e18b21feb89cfdd3a375adab6a68e2) but I can't seem to find where the breaking change is....

**Comment by adrienthiery** [comment]
Removing the `parseColor` function seems to correct the bug for me (see Pull Request #121)

Anybody knows if it makes it break on older versions of React-Native ?

**Comment by m0ngr31** [comment]
Still have this issue on v0.21

**Comment by mmazzarolo** [comment]
Hi! Any info on this? It seems really strange :8ball:

**Comment by dbuarque** [comment]
+1

**Comment by mschipperheyn** [comment]
+1

**Comment by xinthink** [comment]
Sorry for the delay.
The fix is included in v0.3.1, just pushed to NPM, or you can try the latest build on master branch.
