### ISSUE TITLE
Usage of builders

### ISSUE THREAD

**Issue by timjacobi** [xinthink/react-native-material-kit#108]
I would like to understand why this library uses builders all over the place. It kinda works against react's declarative approach.

Instead of using
```JavaScript
render(){
    const ColoredRaisedButton = MKButton.coloredButton()
    .withText("Button")
    .withOnPress(() => alert("pressed"))
    .build();

    return (
      <ColoredRaisedButton />
    );
  }
```
It would be much more intuitive to just be able to use
```JavaScript
<MKButton.ColoredButton text="Button" onPress={() => alert("pressed")} />
```

I'm happy to help if this is something you could imagine for future versions.

**Comment by xinthink** [comment]
There're so many variants of `Buttons`, so I tried the builder pattern to keep it easy but flexible enough to build any kind of buttons you want. But it's not mandatory, it's just an additional choice.

Like what you pointed out, it maybe not a good idea, for a react app, if you have any good suggestion, I'd like to refactor the code. :beer:

**Comment by timjacobi** [comment]
Sure I will create a fork, refactor a couple of components and then let you have a look so you can decide whether you want that in here.

**Comment by alexprice91** [comment]
@timjacobi have you been able to look into this? This could close out a couple other issues also

**Comment by timjacobi** [comment]
@alexprice91 I had seen this on in the README so I guessed it's been solved

```jsx
<MKButton
  backgroundColor={MKColor.Teal}
  shadowRadius={2}
  shadowOffset={{width:0, height:2}}
  shadowOpacity={.7}
  shadowColor="black"
  onPress={() => {
    console.log('hi, raised button!');
  }}
  >
  <Text pointerEvents="none"
        style={{color: 'white', fontWeight: 'bold',}}>
    RAISED BUTTON
  </Text>
</MKButton>
```

Maybe @xinthink can give us an update

**Comment by alexprice91** [comment]
Yeah, it looks like you can use both now. Closing this issue unless there needs to be more clarification.
