### ISSUE TITLE
Minimum SDK required for Material Design?

### ISSUE THREAD

**Issue by jayesbe** [xinthink/react-native-material-kit#110]
I integrated this library into a demo app and tried to build for Android 4.4 which is the minimum for React Native.. however I dont believe its the minimum for Material Design?

Is this true?  Im getting build errors if I target anything less than 5.1  And even then it crashes on startup on Android 5.1.1.  My package only loads on my simulator with Android 6.0.   I don't have a device to test with..   Just wondering if anyone else can confirm.

thanks

**Comment by xinthink** [comment]
This lib is mostly written in JS, so it's not requiring Android L.

The demo is working great on Genymotion Android 4.x emulator
<img width="526" alt="android demo" src="https://cloud.githubusercontent.com/assets/390805/14063829/02409216-f416-11e5-95f0-202de843469b.png">

**Comment by ivanistheone** [comment]
I tried to run an app that uses react-native-material-kit on a Moto G 4.4.4 (kit kat) but if fails with:

     Error while updating property `nativeBackgroundAndroid` of a view managed by: RCTView

So I guess KitKat isn't supported.

**Comment by xinthink** [comment]
It should work, which version of ReactNative are you using?

**Comment by ivanistheone** [comment]
`react-native -v` says

    react-native-cli: 0.2.0
    react-native: 0.20.0

(note very new to react native, it's entirely possible i'm messing something up)

**Comment by ivanistheone** [comment]
For reference, this is the app I was trying to build: https://github.com/InfiniteLibrary/infinite-reader
It uses "react-native": "^0.19.0" internally.   Also uses `react-native-material-kit ^0.2.5`, but I also tried the latest version too.

**Comment by ivanistheone** [comment]
Also, my bundle process might be at fault. This is what I ran:

    react-native bundle --platform android \
                --dev false --entry-file index.android.js \
                --bundle-output android/app/src/main/assets/index.android.bundle \
                --assets-dest android/app/src/main/res/
    ./gradlew assembleRelease
    ./gradlew installRelease

Does this look right?
