### ISSUE TITLE
Cannot evaluate module RNMaterialKit

### ISSUE THREAD

**Issue by anhldbk** [xinthink/react-native-material-kit#111]
I ran command `react-native run-android` and got an issue like this:

![screenshot from 2016-03-07 10-19-17](https://cloud.githubusercontent.com/assets/3270746/13560100/3aca2f70-e44e-11e5-9afc-6b1d700f2e7e.png)

Would you please tell me how to fix that?

**Comment by xelent** [comment]
+1 same problem

**Comment by xinthink** [comment]
the `react-native run-android` should surely work, please follow the Getting started guide

**Comment by Informer** [comment]
+1 me too

**Comment by ringzhz** [comment]
+1

**Comment by Crash--** [comment]
Please read the Getting Started guide, it explains how to link the module both on Android and iOS
