### ISSUE TITLE
Make MKSlider's onPanResponderTerminationRequest prop `()=>false` or configurable

### ISSUE THREAD

**Issue by marcoreat** [xinthink/react-native-material-kit#114]
Right now MKSlider has `onPanResponderTerminationRequest` property hardcoded to `()=>true` ([link](https://github.com/xinthink/react-native-material-kit/blob/master/lib/mdl/Slider.js#L61)). I propose that it should be either `()=>false` or configurable.

The property `onPanResponderTerminationRequest` specifies how the component behaves if another component wants to become the responder for the current gesture. (It's not documented well on the RN's [PanResponder page](https://facebook.github.io/react-native/docs/panresponder.html) but a similar documented property `onResponderTerminationRequest` exists in [the gesture responder system docs](https://facebook.github.io/react-native/docs/gesture-responder-system.html)).

In my app I'm placing a MKSlider component in a View that already responds to gesture events (with a PanResponder). However I'd like the MKSlider to have higher priority than the parent view.

I think that having a slider that doesn't release focus is the most common use case. Actually I can't think of a situation where a MKSlider component would want to stop being the gesture responder. Here is a bug that happens when a SliderIOS component allows other gesture events: https://github.com/facebook/react-native/issues/1046#issuecomment-170347423 .

What do others think?

**Comment by xinthink** [comment]
I'v experimented it with my demo app, which have multiple sliders in a same screen, can't see any difference.
Can you post your code here, and what's your expectation of the behavior of the sliders?

**Comment by marcoreat** [comment]
It's not about multiple sliders on one screen, it's about a slider inside a view that also responds to gesture events. Sorry, preparing a code sample is too difficult for me at the moment (unrelated technical issues). Will update this thread if this changes.

A similar issue was present in RN's SliderIOS and this commit may have more documentation.
https://github.com/facebook/react-native/commit/52ddfd9b51cbaa05176efc8c9dfa7b581be01a97
