### ISSUE TITLE
[enhancement] checkbox doesn't appear properly (a suggestion on Material Design icon usage)

### ISSUE THREAD

**Issue by efkan** [xinthink/react-native-material-kit#118]
Let me start by saying thanks for this awesome work.

I'm sure that I'm not as good as you at Java and React-Native. 
Probably you had thought about the following issue but you didn't for a valid reason on your own.
I guess you had created your own native TickView to perform checking in the checkbox.
Indeed there is a checkbox icon in Material Design here [https://design.google.com/icons/#ic_check_box](https://design.google.com/icons/#ic_check_box).

And the icon color can be changed such as made in [mrn](https://github.com/binggg/mrn/blob/6371cc30fca588e2a177fff3c71354a2055d7358/lib/Checkbox.js#L142) library with together [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). React-native-vector-icons library offers the icon usage as font. So the icon can be colored as you want.

Your theme logic is perfect. I mean just that there are already icons created perfectly by Android.

For instance there are [MDL samples](http://www.getmdl.io/components/index.html#toggles-section/checkbox) as well.

Also I've been discovering this awesome library and that whether I can contribute on or not.

ps: I've created a PR (#117) to correct checkbox appearance a bit.

**Comment by xinthink** [comment]
Thank you for the reporting and the PR!
The reason why I wrote my own `TickView` is that I don't want to include resources (like icons) in this lib.
I think the ideal solution may be giving the flexibility to the users of the lib, one can use `react-native-vector-icons`, commercial licensed artworks..., besides the default built-in `TickView`.
I'll try to do it in the future releases.
