### ISSUE TITLE
[Feature] Cards

### ISSUE THREAD

**Issue by RWOverdijk** [xinthink/react-native-material-kit#12]
Question, and maybe a dumb one..

It looks like both this repo and MaterialKit don't implement cards or lists. Is there a reason for this? Is there something out there for this?

Thanks :)

**Comment by xinthink** [comment]
Hi @RWOverdijk,
Cards and Lists are on the roadmap of RNMK. But the tasks are not started yet.

It'll be amazing if you can help me out with some PRs!

**Comment by RWOverdijk** [comment]
@xinthink I'd love to, but I'm not sure I can. I'm having trouble with boxShadow, mainly. But I'd be willing to try... And even then, my Objective-C is _so-so_

**Comment by xinthink** [comment]
fixed in v0.2.0

**Comment by RWOverdijk** [comment]
Cool :) Thank you!
