### ISSUE TITLE
MKCardStyles is undefined

### ISSUE THREAD

**Issue by liangmicha** [xinthink/react-native-material-kit#123]
Hello I have trouble using MKCardStyles
```
var MK = require('react-native-material-kit');
var {
MKButton,
MKColor,
MKIconToggle,
MKCardStyles
} = MK;
```
when I log MKCardStyles it's undefined... But the others are not undefined.

I'm using version 0.3.0

**Comment by DennisMG** [comment]
Same!

**Comment by DennisMG** [comment]
I fixed it using the example [here](https://github.com/xinthink/rnmk-demo/blob/master/app/cards.js)

**Comment by xinthink** [comment]
It's replaced by the theme system. Please refer to https://github.com/xinthink/react-native-material-kit/releases/tag/v0.3.0
