### ISSUE TITLE
Using a Vector icon in a textfield

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#125]
Is it possible to add a vector icon to a text field, such as in 'Password Input' field: https://www.google.com/design/spec/components/text-fields.html

We are looking to add a show password field to a text input field and would like to use an 'eye'-icon for this.

**Comment by xinthink** [comment]
Maybe it's similar to #115 ?
Unfortunately, it's not in my mind when I wrote the `Textfield` component, but I'll try to do it in the future releases.

**Comment by arkgast** [comment]
Any update on this?
