### ISSUE TITLE
auto grow text field height when typing

### ISSUE THREAD

**Issue by limulidae** [xinthink/react-native-material-kit#128]
is this implemented?

**Comment by xinthink** [comment]
Are you talk about the floating label?
For now, the space is preserved for floating label. It's not changed dynamically.

**Comment by xinthink** [comment]
I'm closing this, if you found some bug, feel free to reopen it.

**Comment by limulidae** [comment]
I am talking about multi-line text field.
Instead of scroll bar, I prefer dynamically adjust text field's height.

**Comment by xinthink** [comment]
@limulidae How can you achieve this with ReactNative's built-in TextInput?

**Comment by limulidae** [comment]
Cannot do this with builtin textinout.

**Comment by Kztka** [comment]
@limulidae 
I recommend to see this.
https://github.com/facebook/react-native/pull/3097
I could build auto grow textinput.
