### ISSUE TITLE
MKButton, MKIconToggle and MKSwitch does not exist

### ISSUE THREAD

**Issue by codepreneur** [xinthink/react-native-material-kit#13]
I just installed material kit on a fresh react-native project (react-native-cli 0.1.4)

```
  "dependencies": {
    "react-native": "^0.10.1",
    "react-native-material-kit": "^0.1.8"
  }
```

and I get these warnings:

```
Warning: Native component for "MKButton" does not existreactConsoleError @ index.ios.bundle:10719
index.ios.bundle:10719 Warning: Native component for "MKIconToggle" does not existreactConsoleError @ index.ios.bundle:10719
index.ios.bundle:10719 Warning: Native component for "MKSwitch" does not existreactConsoleError @ index.ios.bundle:10719
```

![image](https://cloud.githubusercontent.com/assets/3421858/9600636/0f5a50c0-5094-11e5-912b-9e9c0e43f1bd.png)

**Comment by xinthink** [comment]
Hi @codepreneur, sorry for replying late.
I tested with RN 0.10.1 and it works fine. It seems like you forgot to link `libRCTMaterialKit.a`.
Please follow the [Guide](https://github.com/xinthink/react-native-material-kit#getting-started) and try the example code.

**Comment by xinthink** [comment]
Hi @codepreneur, 
I'm going to close this issue, if it still exists, please let me know by a reopening.
