### ISSUE TITLE
RangeSlider onConfirm actually emits onChange

### ISSUE THREAD

**Issue by mcrumm** [xinthink/react-native-material-kit#130]
@xinthink Thanks for adding `onConfirm` for `RangeSlider`.

I tried to update to the latest master, but right now [`onConfirm` is actually emitting `onChange`](https://github.com/xinthink/react-native-material-kit/commit/b1f8db6faa926323f6ed844b635992e26b8e2d98#diff-71e1a6f278451c0fd1619eda3229c9b7R149).

If you'd like, I can submit a PR to fix this.

**Comment by xinthink** [comment]
:scream: Sorry about the mistake!

**Comment by mcrumm** [comment]
No problem -- thanks for fixing it so quickly!
