### ISSUE TITLE
Wrong floating label color in React Native?

### ISSUE THREAD

**Issue by niloms** [xinthink/react-native-material-kit#133]
Hi,

Is color parsing needed in this line (Textfield.js):
`    this.refs.label.setNativeProps({style:{color: utils.parseColor(color)}});`
?

Maybe it should be changed to this:
`    this.refs.label.setNativeProps({style:{color: color}});`

Thanks.

**Comment by Crash--** [comment]
Hi, 

I can't find this line anymore in TextField.js. Does your issue is still relevant with our latest release?

**Comment by niloms** [comment]
I can't find this line now either.
