### ISSUE TITLE
MKTextfield keyboardType not working

### ISSUE THREAD

**Issue by c-h-** [xinthink/react-native-material-kit#137]
Using JSX to create an email address type keyboardType text input does not work. The resulting text field is a standard text field without a specific keyboard type.

Keyboard type docs: https://facebook.github.io/react-native/docs/textinput.html

The text input should show the proper email keyboard and not autocomplete or autocapitalize.

Run on iOS simulator.

```javascript
import {
  MKTextField
} from 'react-native-material-kit';
import styles from './styles';

...

<MKTextField
  textInputStyle={styles.TextfieldText}
  placeholder="Email"
  style={styles.Textfield}
  onEndEditing={(email) => this.setState({email})}
  keyboardType="email-address"
/>
```

<img width="333" alt="screen shot 2016-04-09 at 5 20 09 pm" src="https://cloud.githubusercontent.com/assets/5919164/14406502/567bd33e-fe77-11e5-8aac-0c788f807abe.png">

**Comment by Crash--** [comment]
I just tried and I have the right keyboard with `keyboardType`. But like with RN itself, you have to specify `autoCapitalize` &  `autoCorrect` to not have autocorrect & autocapitalize. This example works great. 

```jsx
<MKTextField
  textInputStyle={styles.TextfieldText}
  placeholder="Test"
  style={styles.Textfield}
  placeholderTextColor="red"
  keyboardType='email-address'
  autoCapitalize="none"
  autoCorrect={false}
/>
```

**Comment by 44kapps** [comment]
I am also having similar issue. keyboard type is not changing to email-address type. instead I am seeing normal keyboard. I tried both keyBoardType='email-address' and keyBoardType="email-address"

              <TextInput style={styles.Input}
                placeholder="Email"
                placeholderTextColor="rgba(255,255,255,0.7)"
                keyBoardType='email-address'
                returnKeyType="next"
                autoCapitalize="none"
                autoCorrect={false}
                onSubmitEditing={() => this.passwordInput.focus()}
                onChangeText={(text) => this.setState({email:text})}
              />

**Comment by c-h-** [comment]
@44kapps try `keyboardType` not `keyBoardType`. Note the lowercase b
