### ISSUE TITLE
Question: is there also a floatedlabel textarea field?

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#14]
Is there also a floatedlabel textarea field?

**Comment by xinthink** [comment]
`mdl.Textfield` has a `floatingLabelEnabled` prop, set to `true` if you want the floating effect.

**Comment by Sherlock92** [comment]
Thanks! Is there a way to set a different color for the label and the underline. I think `tintColor` applies to both currently ? Unfortunately when I apply `tintColor={'#9B9AAE'}` only the underline is changing :(

**Comment by xinthink** [comment]
underline has two colors, `tintColor` for the blurred underline and palceholder text, and `highlightColor` for the focused underline and floating label

please refer to http://www.xinthink.com/react-native-material-kit/docs/Lib/mdl/Textfield.html#props

**Comment by mschipperheyn** [comment]
So, multiline is possible with TextField?

**Comment by xinthink** [comment]
mdl.Textfield is a wrapper of RN.TextInput, so multi-line text should also be supported, but it’s not tested


—

**Comment by xinthink** [comment]
@mschipperheyn If found bugs of multiline or anything else, please open an issue.
