### ISSUE TITLE
get/set makes mdl components incompatible with Webpack/hot load

### ISSUE THREAD

**Issue by clintandrewhall** [xinthink/react-native-material-kit#15]
I've been using this library, but as of 0.1.9, the modules will not load without changing the get/set method of Progress, Slider and Spinner to pure methods.

I have confirmed that changing these to plain functions resolve the issues.  I'll send a PR shortly.  Thanks!

**Comment by clintandrewhall** [comment]
Created simple PRs #16 and #17 to address the issue.

**Comment by xinthink** [comment]
hi @clintandrewhall, thanks for using.

Which version of RN you're using?

**Comment by clintandrewhall** [comment]
I'm using v0.8.0, but I'll test with a later version to be sure.  I'm fairly certain this is an issue related to the webpack hot loader, but I'll confirm and get back to you.

**Comment by clintandrewhall** [comment]
Confirmed: still an issue with 0.10.1

**Comment by xinthink** [comment]
But it's working fine on my Mac, with both RN 0.8 and 0.10, is it an issue of Babel transformer?

I prefer a property to a method, maybe using `Object.define` is better way, what do u think?

**Comment by xinthink** [comment]
Sorry, I meant `defineProperty`, like this:

```js
Object.defineProperty(Slider.prototype, 'value', {
  set: function (value) {
    this._internalSetValue(value);
    this._aniUpdateValue(value);
  },
  get: function () {
    return this._value;
  },
  enumerable: true,
});
```

@clintandrewhall I'd like to know whether it can fix the problem?

**Comment by xinthink** [comment]
hi @clintandrewhall 
I've changed to use `Object.defineProperty`, pushed to master. 
Would you mind giving it a shot? Please let me know if the problem remains.
