### ISSUE TITLE
Checkbox doesn't work on Android

### ISSUE THREAD

**Issue by KarlosQ** [xinthink/react-native-material-kit#155]
I'm trying to do work the checkboxes but they are not working. Other things like TextField or Slider are working.

I import the component: 
```
import {
  MKCheckbox,
} from 'react-native-material-kit';
```
And put inside a View:
```
<View>
<MKCheckbox checked={true} />
</View>
```

But the only thing showing is:
![login](https://cloud.githubusercontent.com/assets/15233913/15118649/7243e8c4-160d-11e6-9257-3631a9de6494.png)

I use Android 5.1 and RN 0.24

**Comment by vladp** [comment]
checkboxes are working for me. 
I suspect you need a style

pick styles from example's style.js
```

const styles = require('../mylocationOfMDKExampleCode/styles');

        <View  style={styles.col}> 
                   <View  style={styles.row}  >
                     <MKCheckbox
                         checked=true
                         onCheckedChange= {(e) => {yourFunctionToReactToChange(e)}}
                     />
                     <Text style={styles.legendLabel}>CheckBoxLabel</Text>
                   </View>
        </View>

```

**Comment by KarlosQ** [comment]
Nop, I try with this styles and nothing: 

```
const testStyle = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  container: {
    flex: 1,
    alignItems: 'stretch',
    backgroundColor: '#F5FCFF',
    padding: 20,
    marginTop: Platform.OS === 'android' ? 56 : 0,
  },
  row: {
    flexDirection: 'row',
  },
  col: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    marginLeft: 7, marginRight: 7,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginTop: 10, marginBottom: 20,
  },
  legendLabel: {
    textAlign: 'center',
    color: '#666666',
    marginTop: 10, marginBottom: 20,
    fontSize: 12,
    fontWeight: '300',
  },
});
          <View  style={testStyle.col}>
            <View  style={testStyle.row}  >
              <MKCheckbox checked={true} />
              <Text style={testStyle.legendLabel}>CheckBoxLabel</Text>
            </View>
          </View>
```

![sin titulo](https://cloud.githubusercontent.com/assets/15233913/15212063/0cd31440-183f-11e6-8466-8e570f0be334.jpg)

**Comment by vladp** [comment]
Hmm, I am puzzled. Mine works very well with 0.3.0 and 0.3.1 on all of the react releases.
On android API 22 and 23 (using Nexus 6 settings). no problem
Are you using Android emulator or Genymotion (I am using Android emulator).

(only thing that does not work for me is React Native Debugging in Chrome..)

**Comment by DennisMG** [comment]
Same here. Checkboxes are not working in the github version of material-kit. Use the npm version instead!

**Comment by colorhaake** [comment]
My checkboxs do not working too.

The reason why that checkboxs are not working I think is the following commit
https://github.com/xinthink/react-native-material-kit/pull/151/commits/871b10b7216800e8c5fb3af21d1fdcbc9babb4d6

When I use the latest version of checkbox, react native will popup warning
`Warning: Failed propType: Invalid props.style key `editable` supplied to `Checkbox`.`

After I remove `editable` props at Checkbox.js, warning is gone, and the checkbox can be clicked again

**Comment by Crash--** [comment]
@colorhaake Just merged a fix in master. Can you confirm that your checkbox work again?

**Comment by colorhaake** [comment]
@Crash-- It works! Thanks for your help
