### ISSUE TITLE
Warning: ReactNative.createElement is deprecated

### ISSUE THREAD

**Issue by dht** [xinthink/react-native-material-kit#158]
I am getting a warning by using this:

const MK = require('react-native-material-kit');

const {
  MKButton,
} = MK;

const ColoredRaisedButton = MKButton.coloredButton()
  .withText('BUTTON')
  .withOnPress(() => {
    console.log("Hi, it's a colored button!");
  })
  .build();

The warning is:
ReactNative.createElement is deprecated

**Comment by vladp** [comment]
+1. I started getting it to, once migrated to 0.25.1

**Comment by Crash--** [comment]
Can you try this patch ?

https://github.com/xinthink/react-native-material-kit/pull/152/files

**Comment by limulidae** [comment]
+1

**Comment by reergymerej** [comment]
[RN 0.25.1 release notes](https://github.com/facebook/react-native/releases/tag/v0.25.1)

**Comment by limulidae** [comment]
v26 is released, btw.

**Comment by Crash--** [comment]
Close this issue for now since RN 0.26 is out and that we gave a [workaround]() to fix issues with it.
