### ISSUE TITLE
Need more detail about iOS and android setup

### ISSUE THREAD

**Issue by phpsmarter** [xinthink/react-native-material-kit#160]
iOS

Add node_modules/react-native-material-kit/iOS/RCTMaterialKit.xcodeproj to your xcode project, usually under the Libraries group
Add libRCTMaterialKit.a (from Products under RCTMaterialKit.xcodeproj) to build target's Linked Frameworks and Libraries list
 I don't understand above path,could you give more detail ?and  android  step 4,I can't catch up with you too. 
By the way excellent work!

**Comment by mmelitzer** [comment]
Use "rnpm install react-native-material-kit", it does the linking for you.
The path node_modules...... is in your project after you installed it using npm .....
The .a file you have to link, click on your project's root in XCode and in the tab Build Phases under Link binary With Libraries click + and the .a file should be under Workspace

**Comment by Crash--** [comment]
@phpsmarter is it better with this [documentation](https://github.com/xinthink/react-native-material-kit/pull/168/files) ?

**Comment by xinthink** [comment]
Maybe we can put more detailed instructions (with screenshots) into a wiki page, which's useful for those who're new to RN. But keep the README document clean and brief, because it's the home page of the project.
