### ISSUE TITLE
Long-Term Planning

### ISSUE THREAD

**Issue by alexprice91** [xinthink/react-native-material-kit#170]
Want to use this thread to launch long-term planning for the app, and how best to use contributors. I want to keep this in the spirit of what @xinthink have done so far.

## Contributor Types

These were some roles that I thought different contributors can have. Some people might fit all roles, but we need them all to move forward with the project.

- `Visionary`: someone who looks at the long term goals of RNMK, and helps point contributors to those goals. 
- `Project Manager:` manages issues, keeps them clean and assigns issues to contributors as needed
- `Helper`: someone who can help the community use RNMK
- `Bug fixer`: someone who can pick up a bug, and fix it
- `Feature implementor`: someone who can hammer out new code for new features

Please comment on which type of role you are, and if you are a `Project Manager` type, please keep note of this

## Issues
It looks like we already have [labels](https://github.com/xinthink/react-native-material-kit/labels). It would be great if we can have project managers use these.

## Long Term Goals
I think it would be worth while looking toward creating long term goals. I would say the longest-term goal, if other people agree, is to looks at building components compatible with [material-ui](http://www.material-ui.com/).

**Comment by alexprice91** [comment]
@xinthink @Crash-- and other contributors, would love thoughts here.

**Comment by xinthink** [comment]
Couldn't agree more @alexprice91 

And I think log term goals may also include: 
- Performance boost
  - By reducing view hierarchies? Considering making more out of native MD components on Android
- Modularizing, long long term 😄 when the lib grows big enough

**Comment by xinthink** [comment]
Useful tools
- A [Slack channel](https://rnmk.slack.com) maybe suitable for discussions amongst the contributors
- [ZenHub](https://www.zenhub.io) may help managing the project
