### ISSUE TITLE
Can not override styles on MKIconToggle

### ISSUE THREAD

**Issue by tume** [xinthink/react-native-material-kit#178]
Upgraded to version v0.3.2 and it seems that MKIconToggle is ignoring the styles that I'm passing to it. It was working in the previous version.

I was using it to make the toggle a bit bigger than the default size so if there is better way to do it now would be interested to know.

**Comment by Crash--** [comment]
Hi, 

Thanks for reporting this issue. How do you currently override the default style? Like that I'll be able to reproduce the same issue and try to fix it.

**Comment by tume** [comment]
Was using like this:

```
<MKIconToggle
  style={{ width: 100 }}
/>
```

**Comment by Crash--** [comment]
I found the issue(It was introduced "long" time ago : https://github.com/xinthink/react-native-material-kit/commit/116760340ca7d734a9768c6d1d464cdddf9e2221#diff-d3366018012b3dfe74baecaf89a0c7d1L86). I'll check with @xinthink to see if there is a good reason for this modification. In the meantime you can patch it yourself to see if it breaks something else ;)
