### ISSUE TITLE
Source directory makes installing from github not possible

### ISSUE THREAD

**Issue by clintandrewhall** [xinthink/react-native-material-kit#18]
NPM assumes that the root directory contains the package.  With the npm package within the 'Source' directory, it cannot be installed directly from github.  In my case, I want to install my branch while #15 is being considered, but can't.

Please reconsider the directory structure? :-)

**Comment by xinthink** [comment]
Yes, you're right. 
Looks like the example app should be moved to a stand-alone repo.
Thanks for the advice!

**Comment by xinthink** [comment]
hi @clintandrewhall 
package.json is moved to the root dir now
