### ISSUE TITLE
MKSwitch dont change while use setState in callback

### ISSUE THREAD

**Issue by linonetwo** [xinthink/react-native-material-kit#189]
Were I use:

              <MKSwitch
                style={styles.isMainPrinciple_Switch}
                trackSize={30}
                trackLength={52}
                onColor="rgba(255,152,0,.3)"
                thumbOnColor={MKColor.Orange}
                rippleColor="rgba(255,152,0,.2)"
                onCheckedChange={(e) => this.setState({newKindsOfPrincipleIsMainPrinciple: e.checked})}
                />

it will not change to the normally checked state, while this does:

              <MKSwitch
                style={styles.isMainPrinciple_Switch}
                trackSize={30}
                trackLength={52}
                onColor="rgba(255,152,0,.3)"
                thumbOnColor={MKColor.Orange}
                rippleColor="rgba(255,152,0,.2)"
                onCheckedChange={(e) => console.log(e)}
                />

strangely.

**Comment by urbanvikingr** [comment]
@linonetwo I am curious to know if this is seen on Android or iOS or both.

**Comment by Crash--** [comment]
Oh, you're right. I'm having this issue with RN 0.29 on iOS. Can you confirm your RN version?

**Comment by linonetwo** [comment]
I use the currently latest version.

And extends, es6 .

**Comment by Crash--** [comment]
@linonetwo Can you try the fix? (#198)

**Comment by dlehdanakf** [comment]
I have same problem...
Is there any help to working `setState`?

RN Version : 0.46.4
react-native-material-kit Version : 0.4.1
