### ISSUE TITLE
React Native Android?

### ISSUE THREAD

**Issue by zth** [xinthink/react-native-material-kit#19]
Hi!
How would one go about installing this for React Native Android? Is it supported? Perhaps a silly question since it's material design, but it'd be nice to be able to use this for a consistent app look on both platforms.

**Comment by xinthink** [comment]
Yes, I've been working on the Android version in the past few days. For compatibility (with devices before Lollipop) reasons, it will not provide a ***native*** material design styled look and feel, the JSX implements will be used, so it'll has a consistent looks and feel across platforms.

**Comment by zth** [comment]
Ahh, that sounds great! Do you mean native look and feel as in it won't be using native elements, or as in that the implementation of the elements will be in pure JS and thus differ some from the native elements because of that?

Thanks for looking into it, looking forward to making this project a standard component in all of my projects. Cheers!

**Comment by xinthink** [comment]
It'll be in pure (or almost) JS, may has some differences from the Android native components.
Can't wait to see your apps built with RNMK! :beer:

**Comment by zth** [comment]
Let me know if you need any help testing! :) Thanks for all of your work and making it open source.

**Comment by xinthink** [comment]
Thanks a lot!

**Comment by zsxsoft** [comment]
Is it support Android now? I cloned the project and copied them to ``node_modules`` just now, and the version was 0.2.0-SNAPSHOT
It seems not work..
![qq 20150927145945](https://cloud.githubusercontent.com/assets/2398785/10121631/78c51cd6-6528-11e5-89b4-8c2d21239cf5.png)

**Comment by xinthink** [comment]
Not yet, I'm still working on it. It's a bit harder than expected.
It's a little buggy at this early stage of RN for Android, and there's some different behaviors between the two platforms.

**Comment by zsxsoft** [comment]
_ (:з」∠)_ I can imagine it.. Good luck to you. By the way, I can't get that why Facebook not(or refuse?)  to provide a <Button> for either iOS nor Android..

**Comment by xinthink** [comment]
fixed in v0.2.0 just released
