### ISSUE TITLE
What is this behavior?

### ISSUE THREAD

**Issue by krokofant** [xinthink/react-native-material-kit#196]
Notice: *Hi, I've been doing React for ~1 week now.*

I have some behavior in my code which I don't know is specific to this package or not. I'd like some help to understand it.

I would like to extend the current raised button for which I have done this
```jsx
const Button = (props) => {
  const parent = MKButton.button()
  const textStyle = parent.textStyle
  console.log('first')
  console.log(parent.textStyle)
  console.log(textStyle)

  return (
    <MKButton
      {...parent.toProps()}
      onPress={props.onPress}>
      {console.log('second')}
      {console.log(parent.textStyle)}
      {console.log(textStyle)}
      <Text style={{
        ...parent.textStyle,
        color: 'green'
      }}>
        {props.text}
      </Text>
    </MKButton>
  )
}
```
And this is the output from my console
<img width="246" alt="react_native_debugger" src="https://cloud.githubusercontent.com/assets/5908498/16705612/ec0ceb7c-458f-11e6-9e54-4b4866599b1c.png">

Why does the second *parent.textStyle* return an array instead of an object?
I assumed I could do
```jsx
style={{
        ...parent.textStyle,
        color: 'green'
      }}
```
But this gives me some errors because I'm spreading an array which makes the keys in the form of 0 1 2...

This is the error-less way
```jsx
style={{
        ...textStyle,
        color: 'green'
      }}
```

Could you provide me any insights? Thanks

**Comment by xinthink** [comment]
This is the behavior of ReactNative's [StyleSheet](https://facebook.github.io/react-native/docs/stylesheet.html), it's immutable, it returns the id of the styles, but not the object. You can provide additional styles to override/extend the old one, for example:

```
style={[ baseStyle, style1, {
    color: 'green'
  }]}
```

**Comment by krokofant** [comment]
Thank you!
