### ISSUE TITLE
Error: Cannot find module './Spinner' from 'index.js'

### ISSUE THREAD

**Issue by picodoth** [xinthink/react-native-material-kit#212]
https://github.com/xinthink/react-native-material-kit/blob/master/lib/mdl/index.js#L9

Spinner.js does not existed,

The existing ones are Spinner.android.js or Spinner.ios.js

Is this on purpose? 

Running test reporting: 

```
 - Error: Cannot find module './Spinner' from 'index.js'
       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
       at Object.<anonymous> (node_modules/react-native-material-kit/lib/mdl/index.js:9:17)
       at Object.<anonymous> (node_modules/react-native-material-kit/lib/index.js:10:10)
```

**Comment by lakeoffaith** [comment]
i think it should not be a problem,rn will require js(.android.js or ios.js) by judge what the os is,

**Comment by Winangel** [comment]
I face the same problem here. 

@lakeoffaith I understand that rn can require the right file when running but I can't get this to work in my tests though as babel try to load a Spinner.js file and not a Spinner.ios.js file...

**Comment by picodoth** [comment]
@lakeoffaith, yes, it's working in real time but I'm having problem with tests. Isn't this a very common issue? What would be a good solution?

**Comment by Winangel** [comment]
@picodoth 
The solution I have found so far is changing the compiler used by a custom one. You need to override de module._findPath function in order to resolve the platform specific dependencies.

You need to create a compiler.js file that looks like this:
```javascript
var fs = require('fs');
var path = require('path');
var babel = require('babel-core');
var origJs = require.extensions['.js'];

var Module = require('module')
var orig_findPath = Module._findPath

Module._findPath = function(request, paths) {
  var filename = orig_findPath(request, paths)
  if (!filename) {
    var cacheKey = JSON.stringify({request: request, paths: paths});
    for (var i = 0, PL = paths.length; i < PL; i++) {
      var basePath = path.resolve(paths[i], request);
      try {
        filename = fs.realpathSync(path.resolve(basePath, 'index.ios.js'), Module._realpathCache);
      } catch (ex) {
        try {
          filename = fs.realpathSync(basePath+'.ios.js', Module._realpathCache);
        } catch (ex) {

        }
      }
      if (filename) {
        Module._pathCache[cacheKey] = filename;
      }
    }
  }
  return filename;
}

require.extensions['.js'] = function (module, fileName){
  var output;
  if (fileName.indexOf('node_modules/') >= 0 && (fileName.indexOf('react-native-') == -1 || fileName.indexOf('react-native-mock') >= 0)) {
    return (origJs || require.extensions['.js'])(module, fileName);
  }

  var src = fs.readFileSync(fileName, 'utf8');
  output = babel.transform(src, {
    filename: fileName
  }).code;

  return module._compile(output, fileName);
};
```

In your package.json file, just replace the test command with:
`"mocha --recursive --compilers js:compiler.js -r test/setup"`

For the record, I found the answer [here](http://lidatang.com/setup-mocha-testing-react-native/)

Hope it will work for you.

**Comment by Crash--** [comment]
Thank you @Winangel for this detailed answer! 

@picodoth Is it ok now?

**Comment by picodoth** [comment]
outdated, closing
