### ISSUE TITLE
[android] Need Fix the readme

### ISSUE THREAD

**Issue by MQZhangThu** [xinthink/react-native-material-kit#214]
My environment is gradle 2.4 on Android.   The `ReactMaterialKitPackage` should be added in the `MainApplication.java` file. 

Moreover, I encountered errors like

 `:react-native-material-kit:prepareReleaseDependencies FAILED FAILURE: Build failed with an exception. * What went wrong:...`.  

I fix this problem by editing some lines of  `node_modules/react-native-material-kit/android/build.gradle` from `dependencies {
    provided 'com.facebook.react:react-native:0.+'
}` to `dependencies {
    compile 'com.facebook.react:react-native:0.+'
}`

**Comment by vinayr** [comment]
+1 
It should be `compile` instead of `provided`.  
Otherwise `react-native run-android` will throw this error - 
```
Project react-native-material-kit: provided dependencies can only be jars. com.facebook.react:react-native:aar:0.32.0 is an Android Library.
:react-native-material-kit:prepareReleaseDependencies FAILED
```
