### ISSUE TITLE
TextField: Cannot read property 'measure' of undefined

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#233]
I'm having a problem that occurs from time to time on the TextField with Floating Label.

This started occurring when I upgraded to redux-form v6.

<img width="370" alt="screen shot 2016-09-13 at 14 56 01" src="https://cloud.githubusercontent.com/assets/384959/18485204/3cfd2220-79c2-11e6-98cf-8f1712b5a750.png">

The associated jsx is:

	<View style={formStyles.formGroup.normal}>
        <TextInput
          {...field.input}
          type={field.type}
          placeholder={field.placeholder}
          secureTextEntry={field.secureTextEntry}
          autoCorrect={field.autoCorrect}
          error = {(field.meta.touched && field.meta.error) || null}
        />
        {field.meta.touched && field.meta.error && <AText style={formStyles.errorBlock}>{field.meta.error}</AText>}
    </View>

The field object looks like this

<img width="744" alt="screen shot 2016-09-13 at 15 00 00" src="https://cloud.githubusercontent.com/assets/384959/18485332/cca416a4-79c2-11e6-9884-8a7a1990f0e2.png">

**Comment by mschipperheyn** [comment]
BTW, I think I started seeing this issue after upgrading to RN 0.32 or 0.33 (can't remember which)

**Comment by Crash--** [comment]
Can you try with this patch ? https://github.com/xinthink/react-native-material-kit/pull/232

**Comment by bakyeono** [comment]
![screenshot_20160914_184404](https://cloud.githubusercontent.com/assets/2022454/18507470/7c0fed32-7aab-11e6-9a6f-357165b7dced.png)

Looks the patch doesn't solve the problem.

**Comment by Sunshow** [comment]
I started seeing this issue after upgrading to RN 0.33.

**Comment by Crash--** [comment]
Can you try with the master branch. We have merged a few fixes for that but not released yet on npm

**Comment by Sunshow** [comment]
after replace node_modules/react-native-material-kit with the master branch files, it works fine.
hope the newer release

**Comment by stief510** [comment]
Can we get a version bump with this?

**Comment by Crash--** [comment]
See my comment here https://github.com/xinthink/react-native-material-kit/issues/244#issuecomment-250446366
