### ISSUE TITLE
How do you change the color of the caret/cursor on a MKTextField...it's always blue

### ISSUE THREAD

**Issue by gkrinc** [xinthink/react-native-material-kit#235]
I'm able to style the MKTextField exact how I want with underline color and size as well as the font, but when the field is focused the blinking caret/cursor is always blue. Is this just part of my iOS settings or something I can style?

**Comment by work2fork** [comment]
+1, same problem

**Comment by gkrinc** [comment]
I was able to change the caret colour by adding this code to AppDeletegate.m

`[[UITextField appearance] setTintColor:[UIColor colorWithRed:0x45/255.0 green:0x22/255.0 blue:0xbb/255.0 alpha:1.0]];`

This change the caret colour for ALL text fields in your app, which is likely the desired behaviour, but something to keep in mind.
