### ISSUE TITLE
Cannot read property startToggle of undefined

### ISSUE THREAD

**Issue by larubbio** [xinthink/react-native-material-kit#244]
After upgrading to RN 0.33 (because of an xcode 8 issue) I'm now getting a redbox error with toggles.  It looks like this is fixed in 6a7a33b8ea7ad8a3c843ebe0200af6119a01c4fe can it be released?

**Comment by Crash--** [comment]
You can use the master version with npm `npm install xinthink/react-native-material-kit`

I tried to contact @xinthink but have no news yet. If it sill the case this WE, I'll fork the project and create a new npm version.

**Comment by Crash--** [comment]
I'm closing the issue since the bug is fixed. ;)
