### ISSUE TITLE
FloatingLabel.measure is undefined in RN 0.33.x and 0.34.x

### ISSUE THREAD

**Issue by quadsurf** [xinthink/react-native-material-kit#248]
Not an issue in RN 0.32.0 but when I upgrade to either RN 0.33 or 0.34 it became an issue, even after rebuilding everything, running rnpm link again, and $ react-native upgrade to re-init all template files.

Issue happens on:
Textfield.js:85

**Comment by Crash--** [comment]
We have to release a new version. This issue is solved in the master branch. Can you use it?
