### ISSUE TITLE
[Feature] Slider with two values

### ISSUE THREAD

**Issue by Crash--** [xinthink/react-native-material-kit#25]
In my use case of a slider, I need to be able to select an interval between 2 values (range of values). I tried to implement it, but didn't figured out how to do that.

If someone else want to look at this; you'll be more than welcome ;)

**Comment by xinthink** [comment]
What will it look like? Could you post a demo, or specification here?

**Comment by Crash--** [comment]
Something like https://github.com/Wildhoney/ngRangeSlider but based on your slider would be great! 

The idea is to allow select an interval with : 
- Min value 
- Max value 
- "step value" (i.e. the value to increment / decrement during each move)

**Comment by awaidmann** [comment]
I needed something similar for a project I'm working on. So I spent the last week building it off of the Slider and Thumb classes. The actual component is complete, but now I need to make it jive with the [Contribution Guide](https://github.com/xinthink/react-native-material-kit/blob/master/CONTRIBUTING.md) as well as create a component for the [demo project](https://github.com/xinthink/rnmk-demo).

Currently, it's called DualSlider, but I will be changing that to RangedSlider. You can find my contributions to [RangedSlider](https://github.com/awaidmann/react-native-material-kit/blob/master/lib/mdl/DualSlider.js) and [Thumb](https://github.com/awaidmann/react-native-material-kit/blob/master/lib/mdl/Thumb.js) at the links provided. I was also sure to update the two index files to expose RangedSlider. 

Question for @xinthink: The guide mentions arranging the components alphabetically, but would you rather it be added under Slider or by it's name Ranged Slider in the `README.md`?

I should have all my changes done by the end of the week. Feel free to take a look at what I have so far and give me any feedback before I submit my PR.

**Comment by xinthink** [comment]
this's fix in #94, thanks @awaidmann
