### ISSUE TITLE
Button with red border and can not click

### ISSUE THREAD

**Issue by mosluce** [xinthink/react-native-material-kit#257]
- RN Version : 0.35.0
- iOS: 10.0
- macOS: 10.12

1. createButton using new MKButton.Builder or other functions
2. put some button and test click
3. console print 2 errors
4. red border around button 
5. can not click buttons
![out](https://cloud.githubusercontent.com/assets/1487051/19629527/7daedaf0-99a9-11e6-84ab-1a09aa31d00d.gif)

Source code
![2016-10-24 5 12 54](https://cloud.githubusercontent.com/assets/1487051/19629529/8785afae-99a9-11e6-8e3b-4b69c111edd2.png)

**Comment by mosluce** [comment]
this is a problem that install package with "yarn",
this is ok by "npm"

**Comment by jcollum** [comment]
This is happening to me too. Are you sure it's a yarn problem? If so did you report it as a bug? Seems like a weird bug.

**Comment by wswoodruff** [comment]
If you guys are seeing a red border around a button and nothing is responding to onPress events and the like, then you need to run `react-native link react-native-material-kit`.

**Comment by jcollum** [comment]
Still happening. I'll submit it as a new bug.

**Comment by jcollum** [comment]
https://github.com/xinthink/react-native-material-kit/issues/324
