### ISSUE TITLE
MKTouchable has no propType, react-native 0.36.0

### ISSUE THREAD

**Issue by martinezguillaume** [xinthink/react-native-material-kit#259]
![image](https://cloud.githubusercontent.com/assets/17292331/19720659/690f4644-9b6f-11e6-8403-c5d18f5ff209.png)

I just updated to react-native 0.36.0 and this is the error I got, anyone in the same problem ?
(react-native-material-kit: ^0.3.3)
refs: #258

**Comment by Crash--** [comment]
Can you try this fix: #258

**Comment by YuukanOO** [comment]
@Crash-- Works for me!

**Comment by Taakn** [comment]
works for me as well thanks

**Comment by vitorebatista** [comment]
Works here too, thanks!

**Comment by martinezguillaume** [comment]
Works for me too !

**Comment by theobouwman** [comment]
Here do I need to add this code?

**Comment by jdpenuliarkorefabrik** [comment]
@Crash-- where do you add this?

**Comment by theobouwman** [comment]
@jdpenuliarkorefabrik https://github.com/xinthink/react-native-material-kit/pull/258/files#diff-baf96da6c3e386136d54a3847c06defd

**Comment by Shinichi52** [comment]
@Crash-- I tried add your commit. but i can't Touch and focus to textbook or button? can you help me?

**Comment by vonovak** [comment]
@Crash-- @xinthink could you do a release with this fix?

**Comment by BigPun86** [comment]
+1

**Comment by jdpenuliarkorefabrik** [comment]
@theobouwman thanks!
