### ISSUE TITLE
publish new version (v.0.3.4) to npm registry

### ISSUE THREAD

**Issue by dannycochran** [xinthink/react-native-material-kit#267]
Currently need to require a specific commit hash of rn-material-kit to get the fix from here:

https://github.com/xinthink/react-native-material-kit/pull/258

e.g. in package.json:

```
...
    "react-native-material-kit": "git://github.com/youennPennarun/react-native-material-kit#cc9ac25",
...
```

Can one of the library admins push a new release, v0.3.4, which is just what's currently on master, and update it on the npm registry? Thank you.

**Comment by BigPun86** [comment]
+1

**Comment by dannycochran** [comment]
@xinthink @Crash--  if you'd like to add me as a collaborator on NPM I can also do this.

**Comment by grubstarstar** [comment]
I've tried replacing the line in package.json as above and have run 'npm install' but I still get the error message after doing 'react-native run-android'. Any ideas?

**Comment by ponty96** [comment]
please has the new release been pushed yet?

**Comment by xinthink** [comment]
Sorry for the delay, I'll do it this weekend.
