### ISSUE TITLE
Create a podspec

### ISSUE THREAD

**Issue by pasviegas** [xinthink/react-native-material-kit#27]
Would be really nice to have a podspec the same way react-native-fbsdk (https://github.com/facebook/react-native-fbsdk/blob/master/react-native-fbsdklogin/react-native-fbsdklogin.podspec) does. 

To install the project in an IOS app with cocoapods woud be as simple as:
```ruby
pod 'react-native-material-kit', :path => 'node_modules/react-native-material-kit'
```

**Comment by xinthink** [comment]
Thanks for the advice. Will look into it.

**Comment by pasviegas** [comment]
If you want I could do a PR :)

**Comment by xinthink** [comment]
Sure, thank you!
