### ISSUE TITLE
"Can't find variable: Text" with MKButton JSX

### ISSUE THREAD

**Issue by ericacooksey** [xinthink/react-native-material-kit#272]
I have the following code for a very simple MaterialButton class:

```
import React, { PropTypes } from 'react'

import { MKButton } from 'react-native-material-kit'

class MaterialButton extends React.Component {
  render() {
    var bgColor = this.props.bgColor
    return (
      <MKButton
        {...MKButton.coloredButton().toProps()}
        backgroundColor={bgColor}>
        <Text>SOME TEXT</Text>
      </MKButton>
    )
  }
}

export default MaterialButton
```

This works perfectly when I remove the line `<Text>SOME TEXT</Text>` (albeit, the button has no text). However, when I keep that line, I persistently get the error "Can't find variable: Text". I can use `.withText` with the Builder just fine. However, the JSX seems to be broken. Is there a fix for this?

**Comment by Mardii-D-King** [comment]
"Text" is a component you need to import like how you import PropTypes and MKButton. When i import it from 'react' that never work so i think your best bet is to import it from 'react-native' like so;

import { Text} from 'react-native';
