### ISSUE TITLE
Change placeholder color

### ISSUE THREAD

**Issue by activelogic** [xinthink/react-native-material-kit#276]
I'm implementing a Textfield with a Floating Label as below.  For some reason, `withTintColor()` has no effect on the placeholder text as described in the documentation.   What do I need to do to make the placeholder text grey instead of black?

```
const EmailInput = MKTextField.textfieldWithFloatingLabel()
.withPlaceholder('Email')
.withTintColor('grey')
.withHighlightColor('grey')
.withTextInputStyle({ color: 'white' })
.withFloatingLabelFont({
  fontSize: 14,
  fontWeight: '200',
  color: 'grey'
})
.withKeyboardType('email-address')
.build();
```

**Comment by te-je** [comment]
You closed this. Did you find a solution?

**Comment by te-je** [comment]
Did you find a solution for this? I'm having trouble with this as well.
