### ISSUE TITLE
text in basic MKTextField is not visible while typing

### ISSUE THREAD

**Issue by jcollum** [xinthink/react-native-material-kit#281]
```

styles.textfield = {
    height: 48, // have to do it on iOS
    marginTop: 60
}

...

  render() {
        return (
            <View>
                <View style={{
                    margin: 20,
                    padding: 20,
                    backgroundColor: "#CCC"
                }}>
                    <MKTextField tintColor={MKColor.Orange} textInputStyle={{
                        color: MKColor.Blue
                    }} placeholder="Text…" style={styles.textfield}/>
                </View>
                <View style={{
                    margin: 20,
                    padding: 20,
                    backgroundColor: "#CCC"
                }}>
                    <TextfieldWithFloatingLabel ref="defaultInput"/>
                    <Text style={styles.legendLabel}>With floating label</Text>
                </View>
            </View>
        )
    }
```

When focus is on another text box: 

![image](https://cloud.githubusercontent.com/assets/704514/21570598/537d862a-ce7c-11e6-844e-90ee409ec4b6.png)

When focus is on top text box: 

![image](https://cloud.githubusercontent.com/assets/704514/21570604/6575b8b6-ce7c-11e6-91f3-3b55a1df146f.png)

When triple clicking top text box's text: 

![image](https://cloud.githubusercontent.com/assets/704514/21570614/7d4acac6-ce7c-11e6-86b9-1e0379acb013.png)

So the text is there, definitely, but I can't see it. Also that placeholder text is right in the middle of the line. 

```
$ react-native --version
react-native-cli: 1.2.0
react-native: 0.39.2
...
"react-native-material-kit": "~0.3.4",
```

**Comment by arjunpola** [comment]
I have the same issue 

react-native-cli: 1.0.0
react-native: 0.39.2

"react-native-material-kit": "^0.3.4",


Works perfectly fine on Android but on iOS I don't see the text until I select a different UI component.

**Comment by quan118** [comment]
You can fix this bug by adding flex:1 in the textInputStype prop

```
<MKTextField
   tintColor={MKColor.Orange}
   textInputStyle={{color: MKColor.Blue, flex:1}}
   placeholder="Text…"
   style={styles.textfield}
/>
```

**Comment by arjunpola** [comment]
@quan118 thank you so much. Yeah, that solved the problem for me.

**Comment by Crash--** [comment]
👍

**Comment by agrass** [comment]
Anyone with RN 0.41+?  I add flexGrow or flex but it still with same problem

**Comment by agrass** [comment]
fixed with ```textInputStyle={{flexGrow: 1, flex: 0}}```

**Comment by alicheh** [comment]
@agrass This solved my other problem, I had to tap exactly on the placeholder to get focus.

**Comment by abuammar** [comment]
i have the same issue unable to solve
