### ISSUE TITLE
Please update to react native 0.40.0

### ISSUE THREAD

**Issue by tuantle** [xinthink/react-native-material-kit#287]
With react native 0.40.0, iOS native headers has been moved to #import <React/RCTUtils.h>. Please update to support this.

**Comment by ishabo** [comment]
I forked it and made a PR: https://github.com/xinthink/react-native-material-kit/pull/289

For now I just point to my branch in the packages.json file:

`    "react-native-material-kit": "git+https://github.com/ishabo/react-native-material-kit.git#react_native_0.40.0_compatability",
`

**Comment by tuantle** [comment]
Awesome. Thanks.

**Comment by Crash--** [comment]
I'll publish a new major version on NPM soon in order to not break existing app.

**Comment by dgdavid** [comment]
@Crash-- Could you also remove unnecessaries `flex: 1` properties? (see #261 )

**Comment by Crash--** [comment]
Done. It's the first time I release a package to NPM so let me know if I've done something wrong :)
