### ISSUE TITLE
Publish lastest version

### ISSUE THREAD

**Issue by pasviegas** [xinthink/react-native-material-kit#29]
Hey xinthink can you publish the latest version with the podspec so I can start using it from the npm registry in one of my projects?

Thanks again

**Comment by xinthink** [comment]
I'd like to publish the next version with fully android support, and I'm very close to finish it, 1~2 days should be sufficient.

**Comment by xinthink** [comment]
v0.2.0 is just released

**Comment by pasviegas** [comment]
Awesome! Thanks! :D
