### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by ChitaGideon** [xinthink/react-native-material-kit#30]
I try to follow the guide add RNMK in my Android project  .
Build failed with an exception
```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/Pamakids-Dev/js/react/graNote/android/settings.gradle' line: 5

* What went wrong:
A problem occurred evaluating settings 'graNote'.
> No signature of method: java.io.File.toPath() is applicable for argument types: () values: []
  Possible solutions: getPath(), length(), toURI(), toURL(), each(groovy.lang.Closure), with(groovy.lang.Closure)

``` 

this is may settings.gradle
```
rootProject.name = 'xxx'

// resolve the symbolic link if any
def resolve(File dir) {
  dir.toPath().toAbsolutePath().toFile()
}

include ':app'

include ':RNMaterialKit'
project(':RNMaterialKit').projectDir = resolve file('../node_modules/react-native-material-kit/android')

```

Is there anything I miss?
I install the package from the git

**Comment by xinthink** [comment]
Which version of Java are you using? `toPath` needs Java 7+

**Comment by xinthink** [comment]
If your Rnmk is not a symbolic link (local module installed with `npm link`), you can ignore the `resolve` step, just use `file`. I'll update the doc. 
But to compile the lib, Jdk 7+ is still required.

**Comment by xinthink** [comment]
hi @ChitaGideon, is the problem fixed?

**Comment by ChitaGideon** [comment]
@xinthink  yes！ After I got your message ,I updated java and everything is ok~

thanks for your wonderful suggestion!
