### ISSUE TITLE
Warning: Failed propType: typeChecker is not a function

### ISSUE THREAD

**Issue by adamrainsby** [xinthink/react-native-material-kit#31]
I'm getting this error from the AccentColoredFab component

This is how I used it.

```
var AccentColoredFab = MKButton.accentColoredFab()
  .withText('+')
  .build();
```

and in render
```
<AccentColoredFab onPress={this.handlePress} />
```

**Comment by xinthink** [comment]
This warning from `MKButton` should be fixed in v0.2.0

But still exists in `Cards` and `Textfield`, will keep track of it

**Comment by adamrainsby** [comment]
Thanks. :smile:

**Comment by Crash--** [comment]
@xinthink How do you solved this issue for MKButton?

**Comment by xinthink** [comment]
By removing built-in property declarations like `shadowColor`

the declaration of `MKPropTypes.font` causes the problem in `Textfield`, don't know why yet

**Comment by despairblue** [comment]
It should use `PropTypes.shape` instead of `PropTypes.objectOf`. See: https://facebook.github.io/react/docs/reusable-components.html

**Comment by despairblue** [comment]
@xinthink what do you think about the PR?

**Comment by xinthink** [comment]
Sorry for replying late, I'm a little busy on my full-time job, will look into it ASSP.
And thank you very much for the PR!
