### ISSUE TITLE
Floating label works incorrectly

### ISSUE THREAD

**Issue by Juxtlie** [xinthink/react-native-material-kit#334]
Platform : Android
React native: 0.44

It happens sometimes
https://www.dropbox.com/s/qdcekazu3meksh1/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-06-05%2014.50.45.png?dl=0

**Comment by minkesh** [comment]
This issue occurs when the component is mounted with defaultValue prop set for it. When the item is in focus then it fixes itself.

**Comment by AhsanAk** [comment]
Any solution?

**Comment by Juxtlie** [comment]
I found resolve. In the Textfield.js add this condition 
 if(this.offsetX){
      this.forceUpdate();
    }

full code 
 _onLabelLayout = ({ nativeEvent: { layout } }) => {
    const x = layout.x;
    const width = layout.width;
    const height = layout.height;
    if (width && !this.offsetX) {
      this.offsetX = ((width - (width * 0.8)) / 2 * -1);
    }

    if (height && !this.placeholderHeight) {
      this.placeholderHeight = height;
    }

    if (width !== this.labelDim.width || height !== this.labelDim.height) {
      this.labelDim = { width, height };
    }
    if(this.offsetX){
      this.forceUpdate();
    }
  };
