### ISSUE TITLE
requesting to upgrade Build Tool Version

### ISSUE THREAD

**Issue by ZeroCool00** [xinthink/react-native-material-kit#342]
when i compile your project i got this error:

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-material-kit'.
      > The SDK Build Tools revision (23.0.3) is too low for project ':react-nat
ive-material-kit'. Minimum required is 25.0.0

Your SDK Build Tools revision (23.0.3), so if we downgrade to 23. its work fine, but we can't, because afterward we are not able to implement other functionality that require build tool version 25.
so please upgrade your build tool version.

i m already using some other library that require version 25. so i cant downgrade.

**Comment by Crash--** [comment]
So if you change this line, it works fine https://github.com/xinthink/react-native-material-kit/blob/master/android/build.gradle#L15 ?

**Comment by ZeroCool00** [comment]
wow.. its that easy.. i thought we are not allow to change third party lib content.  thank you for the knowledge.

**Comment by Crash--** [comment]
You can fork this project and update this file in your fork ;)
