### ISSUE TITLE
RN 0.47.0 build error \node_modules\react-native-material-kit\android\src\main\java\com\github\xinthink\rnmk\ReactMaterialKitPackage.java:25: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by deathemperor** [xinthink/react-native-material-kit#348]
I just got this error when building react-native android. I checked code and RN's code and found that there's a change https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8 in RN 0.47.0 that removed createJSModules method. 

Removing `    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }` in `ReactMaterialKitPackage.java` solved it

Would mind if I submit a PR for this?

**Comment by deathemperor** [comment]
Please check this PR https://github.com/xinthink/react-native-material-kit/pull/347

**Comment by gokulkulkarni1987** [comment]
I am facing the same issue, please let know how to get away with it.

**Comment by deathemperor** [comment]
@gokulkulkarni1987 did you check that PR https://github.com/xinthink/react-native-material-kit/pull/347? it solves the issue. The author didn't merge it but you can apply the code yourself first.

**Comment by gokulkulkarni1987** [comment]
@deathemperor I made the changed locally now, Thank you.
one more thing can u help me with this [issue](https://github.com/xinthink/react-native-material-kit/issues/349). I need to do something urgently and I am not able to proceed further.
I will be able to test your fix, if the above issue is clarified.

**Comment by charleycesar** [comment]
i am facing the same issue but i fix remove @override
