### ISSUE TITLE
react-native-material-kit setup

### ISSUE THREAD

**Issue by gokulkulkarni1987** [xinthink/react-native-material-kit#349]
I am going through the setup links,
The steps mentioned there are Android, Manually. Is it that we have to do either of them or we have to do both?

I tried both way if I do only Android setup button click does not work, if I do both then I run into this [issue](https://github.com/xinthink/react-native-material-kit/issues/348).

**Comment by deathemperor** [comment]
can't you run the `react-native link react-native-material-kit` link command? If you link but something is not right, you should check the manual steps to see the codes that are there.

Anyway I don't really understand your problem, can you show the code? Usually if you reach the point where you can render buttons, the clicks are just something else not the integration process.

**Comment by gokulkulkarni1987** [comment]
@deathemperor I am sorry if am question does not make any sense. I am really new to react native and all its environment.
Currently whats happening is the button is getting rendered but it does not take click.

So If I run the following commands,
`npm install -S react-native-material-kit`
`react-native link react-native-material-kit`
then everything must work right?

**Comment by gokulkulkarni1987** [comment]
@deathemperor I ran those commands and checked the files, the content was not present and hence I manually added all those and button clicks started working.
Thanks a lot

**Comment by deathemperor** [comment]
usually but not always. For me I have to do one of the steps manually. So if you find anything unusual you should check those steps again to make sure it's success. The link command basically finds and insert necessary codes (as in manually) for you. Sometimes it cannot find the pattern => no code was insert.

**Comment by deathemperor** [comment]
No problem. glad I was able to help.

**Comment by tudor2it** [comment]
@gokulkulkarni1987: Can you please mention for which platform you said it worked? Did you try both Android and iOS with the latest versions of React and React-Native on Windows? I would appreciate if you'll give more details because in may case it dosen't work and I tried many versions and configurations on my Windows machine.

**Comment by gokulkulkarni1987** [comment]
@tudor2it I tried on both Android and iOS, it worked on both I use mac for development.
