### ISSUE TITLE
How to change the placeholder color on the fields (not the floating label)?

### ISSUE THREAD

**Issue by JSafaiyeh** [xinthink/react-native-material-kit#356]

**Comment by kiwipxl** [comment]
Use `placeholderTextColor`, which is a react-native TextInput prop.
There was a PR for this back in Feb that used `tintColor` as a fallback if `placeholderTextColor` wasn't set, but it was never accepted for some reason.

**Comment by JSafaiyeh** [comment]
Awesome thanks.
