### ISSUE TITLE
react-native-material-kit incompatible with React 16

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#357]
PropTypes are still being imported through react instead of prop-types. I see that this has been fixed in master but not released. Please release! I see that this has been in the repo for months already

**Comment by mschipperheyn** [comment]
In order to work around this, make sure you are on the latest yarn and add this to your package.json

```
  "resolutions": {
    "react-native-material-kit": "git+https://github.com/xinthink/react-native-material-kit.git"
  },
```

**Comment by wswoodruff** [comment]
Or if you've got `npm5`, this: ```npm install xinthink/react-native-material-kit```
