### ISSUE TITLE
React-native 0.49.2 cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by milkercaki** [xinthink/react-native-material-kit#360]
I received this error when i updated react-native 0.49.2 from 0.43.4.

But it worked fine in the react-native 0.43.4 version.
i just added this import library code but it gives error. 

> const MK = require('react-native-material-kit');

		"react": "16.0.0-beta.5",
		"react-native": "^0.49.2",
		"react-native-elements": "^0.17.0",
		"react-native-material-kit": "^0.4.1",
		"react-native-push-notification": "^3.0.1",
		"react-native-sensitive-info": "^5.1.0",
		"react-native-switch": "^1.1.2",
		"react-native-toast-easy": "^1.0.4",
		"react-native-vector-icons": "^4.4.0",
		"react-navigation": "^1.0.0-beta.13"
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-beta.5" 

![20171007_143655](https://user-images.githubusercontent.com/29991520/31307488-b5481c70-ab6d-11e7-9923-61321845f591.jpg)

_## I Fixed it my problem was Proptypes define._ 

i changed : Node_modules->react-native-material-kit->lib

and replace proptypes define
`import Proptypes from 'react'`
to 
`import PropTypes from 'prop-types'`

MkTouchable.js
Thumb.js
Tick.js
builder.js
mkproptypes.js
utils.js
/mdl/
Button.js
Checkbox.js
IconToggle.js
IndeterminateProgress.js
Progress.js
RadioButton.js
RangeSlider.js
Ripple.js
Slider.js
Spinner.android.js
Spinner.ios.js
Switch.js
Textfield.js

Replace All Define Type. 

and for android-  
node_modules->react-native-material-kit->android->src->main->java->com->ReactMaterialPackager.java    file

and delete `@Override` from this code blog.

```
 @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

**Comment by LifeNow** [comment]
+1

**Comment by ziadalame** [comment]
same issue .. any fix?

**Comment by Froncz** [comment]
+1

**Comment by Crash--** [comment]
It's fixed in `master`. I need to make a new release...

**Comment by mschipperheyn** [comment]
For those using yarn 1.0+, you can also use this workaround

Another way to work around this issue is using yarn 1.0+ and in package.json

```
"resolutions": {
    "react-native-material-kit": "git+https://github.com/xinthink/react-native-material-kit.git"
  },
  "dependencies": {
    "react-native-material-kit": "^0.4.1",
[...]
```

**Comment by milkercaki** [comment]
Thans for replies. 

main problem is proptypes. I think it imported at older versions
`import 'Proptypes' from 'react'`

but new at the new versions it imported from prop-types:

`import PropTypes from 'prop-types';`

Node-modules  -> react-native-material-kit -> lib 

**Change import type in all files,  and it will fix**

**Comment by silintzir** [comment]
+1

**Comment by pudility** [comment]
You can also use the [github repo](https://github.com/xinthink/react-native-material-kit) if you do not want to have to edit the module yourself.

**Comment by anthonycmain** [comment]
+1 urgent for us

**Comment by tbusot** [comment]
Fixed the problem for me. Thank you!
