### ISSUE TITLE
undefined is not an object (evaluating '_react2.PropTypes.bool') on import

### ISSUE THREAD

**Issue by mxk7199** [xinthink/react-native-material-kit#364]
I'm trying to write a hello world program just with the library imported as:
`import { MKButton } from 'react-native-material-kit';`

The hello world program works without the import, but as soon as I insert the line above, I get this:
![image](https://user-images.githubusercontent.com/8741701/31988536-71a3759a-b93d-11e7-8034-afdab9d5d623.png)

I've done the manual imports to the project via WebStorm, am I missing something here?

**Comment by Crash--** [comment]
yep install this package from github and not via npm.

something like npm install xinthink/react-native-material-kit should work

**Comment by almasaeed2010** [comment]
Hello,

This issue still exists in the latest release and is due to the importing of PropTypes from React instead of the prop-type library. The master branch however has this fixed (as it seems). A new minor release would be great!

Thanks!

**Comment by Arshiamidos** [comment]
import React, {Component } from "react";
import PropTypes from 'prop-types';
import {
..
} from 'react-native';
need to add proptypes like this 
otherwise becase conflict with your JS NPM Node verison it makes an error like this
