### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#38]
I realized that in some situation a toggle is a component that can dominate a form too much if it only references a minor aspect. In such situations, a traditional checkbox would be more appropriate. Are there any plans to implement one?

**Comment by Crash--** [comment]
As those ones http://www.getmdl.io/components/index.html#toggles-section/checkbox (see #34) ? Or the default ones displayed by the browser?

**Comment by xinthink** [comment]
@mschipperheyn I think #34 shall fulfill your requirement, as @Crash-- mentioned
