### ISSUE TITLE
Could the default dimensions be removed?

### ISSUE THREAD

**Issue by despairblue** [xinthink/react-native-material-kit#39]
It makes flexbox styling a little awkward:

```jsx
<MKTextField
  style={{
    flex: 1,
    width: undefined
  }}
  placeholder='should take up the whole screen width'
  />
```

Good job btw! :+1:

**Comment by xinthink** [comment]
Sure, I'll remove it.

**Comment by xinthink** [comment]
It seems working fine to put Textfields inside a horizontal box, even with default dimensions

        <View style={{
            flexDirection: 'row',
          }}
          >
          <MKTextField
            floatingLabelEnabled={true}
            placeholder="hello"
            style={{
              flex: 1,
            }}
          />
        </View>

In contrast, without default dimensions, you will have to set the dimension yourself, when the Textfield is inside a vertical container

        <View style={{
            flexDirection: 'column',
          }}
          >
          <MKTextField
            floatingLabelEnabled={true}
            placeholder="hello"
            style={{
              width: 100,  // you have to do this
            }}
          />
          <Text>Vertical box</Text>
        </View>

So wasn't it a convenience to have default dimensions?
Any thoughts?

**Comment by despairblue** [comment]
Probably it should behave like the `TextInput` component:

* parent: `{flexDirection: 'column'}`:
  * it needs a height
  * grows to screen width by default
  * MKTextField needs `{width: undefined}` do behave like that

* parent: `{flexDirection: 'row'}`:
  * it needs a height
  * it needs a width
  * MKTextField has the defaults set, so needs neither (it could be argued that `TextInput`' behaviour is more confusing)

I think diverting from the way `TextInput` works, may lead to some confusion. There are other small details, e.g. if `TextInput` is set to `{flex: 1}` and the parent is set to `row` it will grow to the parent's `height`, but if the parent is set to `column` it will grow the parent's `width`. `MKTextInpute` does neither at the moment (unless the defaults are explicitly set to `undefined`).

I don't know how much of an effort this is and it will definitely justify a major version bump.

A small example to test some style combinations:

```jsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict'

var React = require('react-native')
var {
  AppRegistry,
  StyleSheet,
  TextInput,
  View
} = React
var MKTextField = require('react-native-material-kit').MKTextField

var test = React.createClass({
  render: function () {
    return (
      <View style={styles.container}>
        <MKTextField
          style={[
            styles.input,
            {
              backgroundColor: 'blue'
            }
          ]}
          floatingLabelEnabled={true}
          value='bla'
          placeholder='some placeholder'
          />
        <TextInput
          style={[
            styles.input,
            {
              backgroundColor: 'green'
            }
          ]}
          value='bla'
          placeholder='some placeholder'
          />
      </View>
    )
  }
})

var styles = StyleSheet.create({
  container: {
    marginTop: 60,
    backgroundColor: 'grey',
    height: 200,
    // flexDirection: 'row',
    flexDirection: 'column'
  },
  input: {
    flex: 1,
    // width: 100,
    // width: undefined,
    // height: 60
  }
})

AppRegistry.registerComponent('test', () => test)
```

**Comment by xinthink** [comment]
I removed the default dimensions, it now behave like a RN.TextInput.
But there's some subtile behaviors worth notice, I've put comments in the [demo](https://github.com/xinthink/rnmk-demo/blob/master/app/textfields.js)
