### ISSUE TITLE
How to get text out of a text object

### ISSUE THREAD

**Issue by psbanka** [xinthink/react-native-material-kit#4]
Thanks for this amazing project! This is very easy to use and quite well written.

I started experimenting with `MKTextField.Builder()`, and I quickly realized that I didn't know the best way to get the text values *out* of the element, since there doesn't seem to be any `withOn...` type of handler available for the builder. Looking over the code in https://github.com/xinthink/react-native-material-kit/blob/master/Source/Lib/builder.js#L106, I didn't see anything that popped out.

**Comment by xinthink** [comment]
I'm so sorry, I just forgot about it :scream: 
I'll fix it ASAP.

**Comment by psbanka** [comment]
Awesome! Thanks so much for your quick response!
