### ISSUE TITLE
[Android] MKTextField text entry is jerky; enter char, backspace delete, then char reappears

### ISSUE THREAD

**Issue by esutton** [xinthink/react-native-material-kit#419]
MKTextField text entry is very jerky on Android.  On iOS MKTextField is very butter smooth.  Is anyone else seeing this?

This is what I see every time I type a character:
1) Type a character
2) Character displays for split second
3) Cursor backspace deletes the character entered
4) Character reappears ???

````
    "react": "^16.9.0",
    "react-native": "^0.60.5",
    "react-native-material-kit": "^0.5.1",
````

````
      <MKTextField
        highlightColor={themeStyle.textPrimary.color}
        tintColor={themeStyle.textPrimary.color}
        selectionColor={themeStyle.textPrimary.color}
        floatingLabelEnabled
        label={label}
        maxFontSizeMultiplier={2.0}
        multiline
        value={value}
        placeholder={label}
        editable={!locked}
        style={[styles.textInput, { color: themeStyle.textPrimary.color }]}
        textInputStyle={[styles.textInput, { color: themeStyle.textPrimary.color }]}
        onChangeText={(text) => {
          this.props.actions.setPropertyDb(object, key, text);
        }}
      />
````

**Comment by code-andres** [comment]
Try updating the variable `value` using `setState()`

Get the current state of value
`const value = this.state.value`

Pass the variable to the MKTextField `value={value}` and in the callback of onChangeText update the value state
`(text) => { this.setState({ value: text }) }`

**Comment by esutton** [comment]
@code-andres thank you for your help.

I am closing.  I think this problem was mainly cause by my updating the database each time a key was typed.  Thanks again.
