### ISSUE TITLE
Icon button

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#43]
On Android, when you press the back icon, there is this round click effect. Is there a way to achieve this with this library?

**Comment by mschipperheyn** [comment]
I guess the same question applies to e.g. ContactChips. When I click them I would like to have this round click effect in the background. Maybe the entire Chip should be a button, not sure

**Comment by mschipperheyn** [comment]
That sounds exactly like what I was looking for!

**Comment by xinthink** [comment]
As @Crash-- mentioned, you can use the Ripple component, or you can also treat it as an FAB without backgroundColor and shadow:



```jsx
<MKButton style={{
    justifyContent: 'center',
    alignItems: 'center',
    width: 48,
    height: 48,
    borderRadius: 24,
  }}
  fab={true}
  rippleColor={`rgba(${MKColor.RGBIndigo},.2)`}
  rippleLocation="center"
  >
  <Image source={require('image!plus_dark')} />
</MKButton>
```
