### ISSUE TITLE
When I click a TextField: this._bufferedValue || "").trim is not a function

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#47]
When I click a TextField: this._bufferedValue || "").trim is not a function

**Comment by mschipperheyn** [comment]
Since _bufferedValue is a syntheticEvent, I don't see how you could trim it

**Comment by mschipperheyn** [comment]
Tried react-native 0.13.1 and 0.13.2. Obviously, somewhere the value gets set to the event itself in stead the event payload.

**Comment by xinthink** [comment]
Would you mind post the code reproducing the problem here, and the stack trace?

**Comment by mschipperheyn** [comment]
Sure. Also reproduced this in react-native 0.12

	Error: (this._bufferedValue || "").trim is not a function
	 stack: 
	  Textfield._createClass.get                     index.ios.bundle?…:78198
	  Textfield._aniFloatLabel                       index.ios.bundle?…:78068
	  Textfield._createClass.set                     index.ios.bundle?…:78198
	  Textfield.componentWillReceiveProps            index.ios.bundle?…:78038
	  ReactCompositeComponentMixin.updateComponent   index.ios.bundle?…:9435
	  wrapper [as updateComponent]                   index.ios.bundle?…:6498
	  ReactCompositeComponentMixin.receiveComponent  index.ios.bundle?…:9357
	  Object.ReactReconciler.receiveComponent        index.ios.bundle?…:7393
	  Object.ReactChildReconciler.updateChildren     index.ios.bundle?…:23697
	  ReactMultiChild.Mixin._updateChildren          index.ios.bundle?…:23462
	 URL: undefined
	 line: undefined

**Comment by mschipperheyn** [comment]
Hmm, wait a minute, this might be related to me not extracting props?

      <View style={{flex:1,flexDirection:'row'}}>
        <MKTextField
          floatingLabelEnabled = {this.props.floatingLabel}
          {...this.props}
          />
      </View>

**Comment by mschipperheyn** [comment]
I'm using redux-form with this. It is using it's own event processing on each field, which is part of the props. I have a feeling that maybe it's misbehaving.

**Comment by xinthink** [comment]
Can you print the type of this._bufferedValue? Maybe it not a string?

**Comment by mschipperheyn** [comment]
https://github.com/erikras/redux-form/issues/181

**Comment by mschipperheyn** [comment]
This issue was on redux-form side and is fixed

**Comment by xinthink** [comment]
OK，thanks

**Comment by jiteshwadia** [comment]
@xinthink , Yes I got the same issue today and found that I was assigning number to 'value' property instead of string.

**Comment by agrass** [comment]
I'm getting this error with material-kit 0.5.1 and I'm not working with redux-form

**Comment by akashnits** [comment]
'Value' property requires a String. If you're getting this error, re-check if you're passing String to value property of TextField.
