### ISSUE TITLE
flatButton: TypeError: expected dynamic type 'int64', but had type 'string'

### ISSUE THREAD

**Issue by adambene** [xinthink/react-native-material-kit#48]
The following error is raised when using flatButton on Android: `TypeError: expected dynamic type 'int64', but had type 'string'`.

If I comment out the line containing `withBackgroundColor(...)` in function flatButton() in Button.js it works fine.

This also raises the error: `(new MKButton.Builder()).build()`
This is ok: `(new MKButton.Builder()).withStyle({}).build()`

**Comment by xinthink** [comment]
Which version of RN are you using?

Would you please try the demo? https://github.com/xinthink/rnmk-demo/blob/master/app/buttons.js#L52

**Comment by adambene** [comment]
I am using version 0.2.2.

The demo also throws the same error when choosing Buttons from the starting screen.
The demo installed the same version (0.2.2).

**Comment by xinthink** [comment]
The demo is working fine on my Mac.
Which version of ReactNative are you using? This is a issue of ReactNative, but should be fixed in RN v0.12.0

**Comment by adambene** [comment]
I am using ReactNative v0.13.2.
