### ISSUE TITLE
[MKTextField] How to get input event like RN.TextInput?

### ISSUE THREAD

**Issue by apolkingg8** [xinthink/react-native-material-kit#5]
Thanks for this awesome project, the material design effect really perfect. But I have some problem with MKTextField: How can I get input area events like `onChangeText `, `onEndEditing ` and other `on*` in [RN.TextInput](http://facebook.github.io/react-native/docs/textinput.html#content)? I can't find anything about that in README or `MKTextField.js`, it's really hard to work without these event callbacks.

**Comment by xinthink** [comment]
I'm sorry for missing these important features, I'll try my best to fix it ASAP.
Thank you for the interest and reminding.
