### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by oliviertassinari** [xinthink/react-native-material-kit#51]
Hi, I'm one of the maintainers of https://github.com/callemall/material-ui.
I dream in a world where I could use the same components to target `react-dom` (the browser) and `react-native` (iOS and Android).

So, do you think that It could be possible to achieve this?
It would be great if we can find a way to join forces.
I think that we would at least need to share the same API. But since we are using inlined-style, I'm wondering if we can't share more.

**Comment by Crash--** [comment]
Hi, 
See #50, we're currently talking about merging some libs together to create something great for react-native. Your POV could be useful!
