### ISSUE TITLE
[Slider] improve responsiveness

### ISSUE THREAD

**Issue by sooth-sayer** [xinthink/react-native-material-kit#52]
I see two issues using Slider.
1. During touch Thumb does follow my finger with some lag.
2. When I move finger outside slider during touch Thumb stop to respond. (https://www.dropbox.com/s/iwb5utzxu9jw7b3/VID_20151106_182304.mp4?dl=0)

I can fix it using standard PanResponder (http://facebook.github.io/react-native/docs/panresponder.html). Will you merge such pull request?

**Comment by xinthink** [comment]
Sure, PRs are always welcome
And apologize for replying late
