### ISSUE TITLE
invoke 'undefined' object measure function in Textfield.js

### ISSUE THREAD

**Issue by jaynsw** [xinthink/react-native-material-kit#56]
This happens when the current page quick unmounted. The code should be changed more defensive.

_doMeasurement() {
    if (this.refs.input) {
      this.refs.input.measure(this._onInputMeasured.bind(this));
      if (this.props.floatingLabelEnabled) {
        this.refs.floatingLabel.measure(this._onLabelMeasured.bind(this));
      }
    }
  }

**Comment by Crash--** [comment]
Hi,

Could you make a PR with a more defensive code?

**Comment by xinthink** [comment]
looks like I should refactor all the `onMeasurement` stuff, or switch to `onLayout`

**Comment by mikedizon** [comment]
+1

**Comment by peterlazar1993** [comment]
+1 @mikedizon fix worked for me.
