### ISSUE TITLE
npm WARN install Couldn't install optional dependency: Unsupported

### ISSUE THREAD

**Issue by linonetwo** [xinthink/react-native-material-kit#58]
$ npm i -S react-native-material-kit
npm WARN install Couldn't install optional dependency: Unsupported
aaa@0.0.1 /home/aaa/ReactNative/aaa
└── react-native-material-kit@0.2.2 
  

Does that matter?

**Comment by xinthink** [comment]
hi @lineves, did you figure it out?

**Comment by lineves** [comment]
no, I can use components without error, seems it doesn't matter, some other thins from npm show the same warning.

**Comment by xinthink** [comment]
@linonetwo I'm going to close the issue, cause RNMK doesn't depend on any library other than RN
