### ISSUE TITLE
[MKTextField] lost focus when component rerender.

### ISSUE THREAD

**Issue by apolkingg8** [xinthink/react-native-material-kit#6]
Thanks for your quick fix :zap: , but I found another issue about TextFiled events. 

I did something like this:
```js
_onBlur = ()=> {
  cl(`onBlur`)
  this.setState({
    upper: false,
  })
}

_onFocus = ()=> {
  cl(`onFocus`)
  this.setState({
    upper: true, // let the component upper, avoid hided by keyboard
  })
}
```
but when I triggered `onFocus` and ran into `setState` => `render` flow, the `TextFiled` lost focus and triggered `onBlur`. That not happened with `RN.TextInput `. Any ideal about that?

**Comment by xinthink** [comment]
Hi @apolkingg8, can you post the complete code here? 
It seems like I'm not reproducing the problem.

![textfield-events](https://cloud.githubusercontent.com/assets/390805/8951949/26faa4fe-3605-11e5-933c-980aa8ceba6d.gif)

```jsx
const TextFields = React.createClass({
  getInitialState: function() {
    return {
      text: null,
      upper: false,
    };
  },
  _onChange: function(e) {
    console.log('text', e.text);
    this.setState({text: e.text});
  },
  _onBlur: function() {
    this.setState({
      upper: false,
    });
    console.log('blur', this.state.upper);
  },
  _onFocus: function() {
    this.setState({
      upper: true,
    });
    console.log('focus', this.state.upper);
  },
  render: function() {
    return (
      ...
      <MKTextField
        ...
        onTextChange={this._onChange}
        onBlur={this._onBlur}
        onFocus={this._onFocus}
      />
```

**Comment by apolkingg8** [comment]
Hi @xinthink, sorry the complete code is hard to split, but I found something maybe cause my issue.
```js
// it works fine
<MKTextFiled
  style={inputStyle}
  onChangeText={this._onTextChange}
  onBlur={this._onBlur}
  onFocus={this._onFocus}
  placeholder='Search keywords...'
  />
```
```js
// it cause this issue
class MyTextFiled extends ReactComponent {
    render = ()=> {
        var TextFiled = new MKTextField.textfieldWithRippleAndFloatingLabel()
            .withPlaceholder('Search keywords...')
            .withStyle({
                width: 232,
                height: 38,
            })
            .withOnFocus(this.props.onFocus)
            .withOnBlur(this.props.onBlur)
            .build();

        console.log(this.props)

        return (
            <TextFiled
                {...this.props}/>
        )
    }
}

...

render (
<MyTextFiled
  style={inputStyle}
  onBlur={this._onBlur}
  onFocus={this._onFocus}
  />
)
```
I don' know why but it seams only happened when using build method like `new MKTextField.textfieldWithRippleAndFloatingLabel()`, maybe I missed something about lifecycle?

**Comment by xinthink** [comment]
The latest commit 16c82b6 will allow tags made by builder to accept properties, you may want to give it a shot. But it's not pushed to npm yet, you may have to checkout the master branch.

It allows:
```jsx
var MyTextFiled = MKTextField.textfieldWithRippleAndFloatingLabel().build();
....
render() {
  return <MyTextFiled style=... onBlur=.... />;
}
```

And I apologize for the bad idea to build components inside the render method, because the component will be built again whenever the render method is called. I've already refactor the examples.

**Comment by apolkingg8** [comment]
Awesome! :beers:
