### ISSUE TITLE
MKTextField onBlur isn't bubbling up the event object.

### ISSUE THREAD

**Issue by kristian-puccio** [xinthink/react-native-material-kit#66]
When I add an onBlur function to MKTextField the event object isn't being passed to my function.

I'm pretty sure it's to do with this line: https://github.com/xinthink/react-native-material-kit/blob/9466ad5b35fd018bdd3e0e6ecdb748ff1c3e7b00/lib/mdl/Textfield.js#L428

I'll create a pull request to fix this.

**Comment by kristian-puccio** [comment]
#67

**Comment by xinthink** [comment]
thanks @kristian-puccio, but why do you need an object on the blur event? it seems to be a pretty simple state.

**Comment by kristian-puccio** [comment]
I use it with redux-form and thats the way that library works, it extracts
the value from there.

Plus I think a few other things, like what type of widget generated the
event.

**Comment by xinthink** [comment]
OK, I'll merge the PR, thanks again!
