### ISSUE TITLE
Text and Password inputs hold different default styles

### ISSUE THREAD

**Issue by Alex-iFactory** [xinthink/react-native-material-kit#68]
Hi mate,

I built two elements:

```jsx
    const PasswordInput = mdl.Textfield.textfieldWithFloatingLabel()
        .withPassword(true)
        .withPlaceholder('Password...')
        .withHighlightColor('#fff')
        .withTintColor('#fff')
        .withUnderlineSize(1)
        .withTextInputStyle([styles.inputElement])
        .withStyle([styles.textfieldWithFloatingLabel])
        .build();

    const UsernameInput = mdl.Textfield.textfieldWithFloatingLabel()
        .withPlaceholder('Username...')
        .withHighlightColor('#fff')
        .withTintColor('#fff')
        .withUnderlineSize(1)
        .withTextInputStyle([styles.inputElement])
        .withStyle([styles.textfieldWithFloatingLabel])
        .build();
```

which are laid out as follows:

```
                    <View style={[styles.flexTwo, styles.paddedContainer]}>
                        <View>
                            <UsernameInput />
                        </View>
                        <View>
                            <PasswordInput />
                        </View>
                        <View style={styles.forgotContainer}>
                            <Text style={[styles.colorGrey, styles.alignRight]}>Forgot Password</Text>
                        </View>
                    </View>
```

But end up getting the following in my render:

![image](https://cloud.githubusercontent.com/assets/5687739/11915877/48eb903e-a705-11e5-9aff-b918f1110d02.png)

**Comment by xinthink** [comment]
hi @Alex-iFactory , did you mean the different font of the password hint text?

Unfortunately, it's the default behavior of Android native EditText component. Please refer to http://stackoverflow.com/questions/3406534/password-hint-font-in-android

**Comment by Alex-iFactory** [comment]
@xinthink thats right,

Would it not make sense to set the default typeface on textPassword elements? Or would this conflict somehow.

Cheers

**Comment by xinthink** [comment]
As mentioned in [this answer](http://stackoverflow.com/a/3444882/679563), it needs works on the native side.
The problem is there no way to access custom font setting from StyleSheet (it just return an id), so it may need a dedicated prop for `hintFont`, and it better also works on iOS.

I'll dig into it later, and any forms of contribution is welcome :beer:

**Comment by vonovak** [comment]
with RN 0.26 this is not an issue any more.
in RN textfield, you can now set font family sans serif and the font will look right
with MKTextField you don't even have to set it, it seems it is somehow taken care of already

**Comment by alexprice91** [comment]
@vonovak nice! thanks for noticing.
