### ISSUE TITLE
0.9.0-rc fails

### ISSUE THREAD

**Issue by ethandt92** [xinthink/react-native-material-kit#7]
You are probably aware of this change.

https://github.com/facebook/react-native/commit/961c1eb42904a4d5516fd7939ba14bc0625309d3

0.9.0-rc adds event counts so RCT_TEXT_EVENT_HANDLER needs to include eventCount

**Comment by xinthink** [comment]
Thank you pointed out this.
I'm not moving to RN 0.9 yet, but I will deal with it as soon as possible.
