### ISSUE TITLE
Debug in Chrome causes UI to become unresponsive in Android

### ISSUE THREAD

**Issue by shankiesan** [xinthink/react-native-material-kit#71]
First, I'd like to say that this is a great project. Really well executed

However, I've got a little bug. I think it's to do with RNMK and not React Native itself as I've only seen this behaviour in projects using RNMK.

If I have RNMK components in my view and enable Debug in Chrome in Android, the UI becomes unresponsive. If I console.log the results of onPress, I will often get the results of the first press – but all subsequent animations freeze and the UI is unresponsive until I Reload JS.

I'm using 0.2.4 of RNMK on RN 0.1.7 on Android 5.1.

My app is pretty simple at the moment – it's [here](https://github.com/shankiesan/cbc-payments).

FWIW, the packager also seems to freeze when this happens – the screenshot below shows white lines with successful loads of the JS package – and the bottom line is what happened when I've tried to debug in Chrome – it seems to be hung waiting for the JS package.
![screen shot 2016-01-02 at 10 23 28](https://cloud.githubusercontent.com/assets/2608862/12074164/0473664c-b13d-11e5-9ee8-fea2dd8d917c.png)

**Comment by xinthink** [comment]
Hi @shankiesan, thanks for reporting.
Unfortunately, don't have any idea so far. Will keep trying.
How does it work on iOS?

**Comment by shankiesan** [comment]
Hi @xinthink thanks for getting back to me.

Infuriatingly, since I posted this issue it's starting working again. I'll close the issue for now, but if I encounter it again I'll test the failing code on iOS and report back to this issue.

Cheers

**Comment by thessem** [comment]
This is currently an issue for me, it works fine on iOS though. I'm using RN 0.20

**Comment by johnwayner** [comment]
I'm seeing this, too (RN 25.1).  But I'm not using material kit, so it's likely a core react native issue.

**Comment by johnwayner** [comment]
I figured out why this was happening to in my case.  I had left my genymotion instance running for a while and the clock had skewed horribly.  React Native use a native poly fill for timers (RCTimer) which attempts to compensate for delays in the javascript-to-native bridge.  When debugging in Chrome, the javascript engine's current time is the host systems, but the timer code doing the compensation is running in the emulator.  This causes huge compensation times that result in all timed functions (via setTimeout, setInterval) never firing.

Maybe this isn't the issue here, but since I ended up here due to this, perhaps others will too.

Otherwise, sorry dredge up an old issue :)

**Comment by shankiesan** [comment]
@johnwayner so are you saying that you simply resolved the issue by restarting genymotion? I am indeed using setTimeout and setInterval quite a lot in my app

**Comment by johnwayner** [comment]
After a discussion with Genymotion, we came to the conclusion that while my laptop was asleep the emulator was losing time.  This caused the emulator's time to be way off.  If your emulator's time is not different than your computer's, you have a different issue, unfortunately.

However, if they are different (even just a little), you should be able to reset the time manually or by restarting the emulator (I may have had to totally reset the emulator...I can't recall right now).

Once the clocks are in sync, the compensation time calculation should work properly and your callbacks will be called.  Unless you have a different issue.

**Comment by shankiesan** [comment]
Thanks, I'll try that next time it doesn't work. Seems to be working now, and it didn't at various times in the past, so your clock sync issue certainly is plausible!
