### ISSUE TITLE
Getting dependency error when installing

### ISSUE THREAD

**Issue by Sexycrets** [xinthink/react-native-material-kit#75]
Hi, thank you for this package, the doc is well written too.

I installed it just fine the first time. When I got the "MKTouchable/TickView does not exist" error (https://github.com/xinthink/react-native-material-kit/issues/53) I removed the package and installed it again but is not installing anymore, see output below. Any ideas?

```
$ npm i -S react-native-material-kit
npm WARN peerDependencies The peer dependency react-native@>=0.16.0 <1.0.0 included from react-native-material-kit will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "react-native-material-kit"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.13
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.18.0-rc does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-material-kit@0.2.5 wants react-native@>=0.16.0 <1.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     ....../npm-debug.log
```

Same result with ```npm install react-native-material-kit```

**Comment by sebathi** [comment]
Have the same issue. :(

**Comment by xinthink** [comment]
Sorry for replying late.
Please remove the `peerDependencies` declaration and try again as @gre described in #74, which already merged into mater branch.

**Comment by Sexycrets** [comment]
It works now thank you
