### ISSUE TITLE
Could not find method compile() for arguments [project ':RNMaterialKit'] on project ':app'

### ISSUE THREAD

**Issue by kozmk** [xinthink/react-native-material-kit#76]
When I run the command "react-native run-android" :

![image](https://cloud.githubusercontent.com/assets/8536648/12206785/a5347914-b664-11e5-8276-cf4939b3d304.png)

![image](https://cloud.githubusercontent.com/assets/8536648/12206793/bb4faf02-b664-11e5-9eb0-8ccc2647bfb7.png)

![image](https://cloud.githubusercontent.com/assets/8536648/12206757/77912d0e-b664-11e5-8957-ccf8209a5b69.png)

**Comment by mazicky** [comment]
Try to put 'compile project(':RNMaterialKit') inside dependencies

**Comment by xinthink** [comment]
Sorry for replying late.
As @mazicky mentioned, `compile project(':RNMaterialKit')` should be include as a dependency, please refer to this example: https://github.com/xinthink/rnmk-demo/blob/master/android/app/build.gradle#L28

I'll update the README document, to put it more clearly.
