### ISSUE TITLE
failed to find Build Tools revision 23.0.2

### ISSUE THREAD

**Issue by vincentfretin** [xinthink/react-native-material-kit#77]
Why did you update buildToolsVersion from "23.0.1" to 23.0.2?
https://github.com/xinthink/react-native-material-kit/commit/78ffeac2922350074e7d0004a29ffa905f755d13#diff-7ae5a9093507568eabbf35c3b0665732R15

I now have this issue when executing react-native run-android:
A problem occurred configuring project ':RNMaterialKit'.
> failed to find Build Tools revision 23.0.2

With RN 0.17.0, I have android/app/build.gradle with buildToolsVersion "23.0.1"
It doesn't seem to have a 23.0.2 update for android sdk.

If I change node_modules/react-native-material-kit/android/build.gradle to 23.0.1, it works fine again.

**Comment by mazicky** [comment]
+1

**Comment by aymericbouzy** [comment]
I have this issue again with version 0.3.4 : 
```
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-material-kit'.
   > failed to find Build Tools revision 23.0.3
```
I have double checked Build Tools revision 23.0.3 are installed. Is there a fix?

**Comment by aymericbouzy** [comment]
I just found the fix : my `$ANDROID_HOME` was not correct. Setting it to the result of `which android` solved it for me.

http://stackoverflow.com/a/38181490/3995091

No need to reopen this issue.

**Comment by aymericbouzy** [comment]
Installing build tools with Android Studio rather than Android SDK solved it for me. http://stackoverflow.com/a/39068538/3995091
