### ISSUE TITLE
Floating label disappears when an event triggers

### ISSUE THREAD

**Issue by Taakn** [xinthink/react-native-material-kit#79]
Hello,

I am faced with the following problem : when an event triggers (for instance `onTextChange={(text) => this.setState({email: text})}` or for a button `onPress={this.handleSignIn}` then the floating label doesn't stay in place after `onBlur` and goes back into hiding.

Sample code:

< TextField
  ref='email'
  placeholder="email address"
  autoFocus={true}
  onTextChange={(text) => this.setState({email: text})}
/>

where TextField is:
var TextField = React.createClass({

render() {
return < MKTextField
      tintColor={MKColor.Grey}
      highlightColor={MKColor.Green}
      textInputStyle={{color: MKColor.Black}}
      floatingLabelEnabled= {true}
      floatingLabelFont={{
        fontSize: 12,
        color: MKColor.Grey
      }}
      floatingLabelAniDuration = {100}
      style={styles.textField}
      {...this.props}
      />;
    }
});

**Comment by xinthink** [comment]
Sorry, would you mind explain the code a little bit? In the above code snippet, it looks like the `TextField` is not a `MKTextFiled`?

I try this in my demo, and it works fine:
```
<MKTextField
  ref="defaultInput"
  floatingLabelEnabled={true}
  placeholder="Hello"
  onTextChange={(t) => this.setState({email: t})}
/>
<Text style={styles.legendLabel}>With floating label {this.state.email}</Text>
```

**Comment by KelseyRegan** [comment]
Looks like he is missing the "<MKTextField " right after return.

I ran into this same issue actually.  To repro, all you need to do is type something in the field, then without leaving the field, trigger a state change in your view (so the render method of MKTextView gets called).  Then, trigger an 'onBlur' by selecting another field, and you will see the floating label disappear.

**Comment by KelseyRegan** [comment]
I might have figured it out actually.  In Textfield.js, this.bufferedValue is empty, so the floating label gets hidden.

**Comment by Taakn** [comment]
@xinthink yes I incorrectly copied and pasted my code, @KelseyRegan is right sorry about that. I was missing <MKTextField in the render section. I corrected the sample code.

**Comment by KelseyRegan** [comment]
@xinthink 
My PR fixes this issue: https://github.com/xinthink/react-native-material-kit/pull/85

**Comment by xinthink** [comment]
Thanks @KelseyRegan, I'll look into it later.

**Comment by Taakn** [comment]
@xinthink @KelseyRegan I've been testing and unfortunately it's not working if I'm loading an existing record in a form and using `defaultValue` to setup the value.

In that case the label is correctly floating, but if I blank out the field the floating label stays floating up and does not disappear. The placeHolder text is there (so I have both the placeHolder and the floating label).

Thanks so much

**Comment by Taakn** [comment]
Don't know if that's related, but if I'm using `master` with React Native 19.0-rc it works on iOS, but not on Android. I am getting:

`undefined is not an object. (evaluating 'UIManager.AndroidTextInput.Constants.TextAlign[this.props.textAlign]')`

**Comment by Taakn** [comment]
Don't know if that's related, but if I'm using `master` with React Native 19.0-rc it works on iOS, but not on Android. I am getting:

```
undefined is not an object. 
(evaluating 'UIManager.AndroidTextInput.Constants.TextAlign[this.props.textAlign]')
```

line 494 TextInput.js in `_renderAndroid`
