### ISSUE TITLE
Button Does Not Work (Native component for "MKTouchable"/"Tickview" does not exist)

### ISSUE THREAD

**Issue by Sexycrets** [xinthink/react-native-material-kit#82]
When running I receive the 2 warnings mentioned in the subject and the button does not react when clicked: no visual feedback and the console.log in the onPress event is not executed. (I tried on iOS simulator).

I used the following code copy pasted from the documentation example:

```
const MK = require('react-native-material-kit');
const {
  MKButton,
  MKColor,
  MKTouchable
} = MK;
...
<MKButton
            backgroundColor={MKColor.Red}
            shadowRadius={2}
            shadowOffset={{width:0, height:2}}
            shadowOpacity={.7}
            shadowColor="black"
            onPress={() => {
              console.log('hi, raised button!');
            }}
            >
            <Text pointerEvents="none"
                  style={{color: 'red', fontWeight: 'bold',}}>
              RAISED BUTTON
            </Text>
          </MKButton>
```

Warnings:
```
ExceptionsManager.js:78Warning: Native component for "MKTouchable" does not existreactConsoleError @ ExceptionsManager.js:78console.error @ YellowBox.js:49warning @ warning.js:42requireNativeComponent @ requireNativeComponent.js:53(anonymous function) @ MKTouchable.js:62requireImpl @ require.js:61require @ require.js:21(anonymous function) @ Ripple.js:12requireImpl @ require.js:61require @ require.js:21(anonymous function) @ IconToggle.js:20requireImpl @ require.js:61require @ require.js:21(anonymous function) @ index.js:5requireImpl @ require.js:61require @ require.js:21(anonymous function) @ index.js:7requireImpl @ require.js:61require @ require.js:21(anonymous function) @ screen-lovers-profile.js:3requireImpl @ require.js:61require @ require.js:21(anonymous function) @ main.js:9requireImpl @ require.js:61require @ require.js:21(anonymous function) @ index.ios.js:4requireImpl @ require.js:61requireImpl @ require.js:29require @ require.js:21(anonymous function) @ index.ios.js.js:1messageHandlers.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:33

ExceptionsManager.js:78Warning: Native component for "TickView" does not exist
```

Any ideas?

Thanks!

**Comment by Sexycrets** [comment]
Solved. After the issue with the npm not installing because of the peerDependencies the library was removed from the XCode project. 

Adding it back fixed the issue.

**Comment by gluwa** [comment]
Experiencing the same problem. Trying to figure out how @Sexycrets fixed it.

**Comment by Crash--** [comment]
Be sure to have linked the project. 

The easiest way is to install [rnpm](https://github.com/rnpm/rnpm) then in your project you have to run : 
`rnpm link`

Or by doing `rnpm link react-native-material-kit`

**Comment by gluwa** [comment]
Thanks @Crash-- .
I did it but rnpm says they were already linked, and I am still getting the warnings.

```
$ rnpm link
rnpm-link info Android module react-native-material-kit is already linked 
rnpm-link info iOS module react-native-material-kit is already linked 
```

I will keep looking for the root cause, and will update here when I solve the problem.

**Comment by Crash--** [comment]
The warning says that the NativeComponent is not reachable. If these components are well linked... Maybe you can uninstall react-native-material-kit (first with npm and then remove it from your XCode project) and then install it again.

**Comment by gluwa** [comment]
Will try that now.

**Comment by gluwa** [comment]
Fixed. Thanks @Crash-- .
I had to relaunch React Packager during the process @Crash-- has recommended, and I wonder if it has anything to do with the problem.

**Comment by jhabdas** [comment]
Also had this problem and simply running `react-native run-ios` to rebuild the iOS project corrected the error.

**Comment by jcollum** [comment]
Just ran into this and it was stopping the app from using MKCheckbox (weird red lines around the checkbox and it wasn't picking up its events). Had to kill my React Packager and run `react-native run-ios` again. Now it all works right.

**Comment by AndrewHenderson** [comment]
I'm trying to use `MKButton` in React Native's `Navigator.NavigationBar`. Their docs instruct users to use `TouchableHighlight` for the buttons. Is `MKTouchable` the equivalent of that? Based on the comments in `MKTouchable.js`, it doesn't seem like it. When attempting to use `MKTouchable` in the `NavigationBar`, I receive the following error:

<img width="312" alt="screen shot 2016-10-29 at 2 42 24 pm" src="https://cloud.githubusercontent.com/assets/1031565/19832935/f12789ce-9de5-11e6-8146-fc6eed762473.png">

Here's my code:

```jsx
navigationBar={
          <Navigator.NavigationBar
            style={styles.navbar}
            routeMapper={{
              LeftButton: (route, navigator, index, navState) =>
              {
                if (route.index === 0) {
                  return null;
                } else {
                  return (
                    <TouchableHighlight onPress={() => navigator.pop()}>
                      <Text style={styles.navbarButton}>Back</Text>
                    </TouchableHighlight>
                  );
                }
              },
              RightButton: (route, navigator, index, navState) =>
              {
                if (route.index === routes.length - 1) {
                  return null;
                } else {
                  return (
                    <MKTouchable {...coloredButtonProps}
                                 onPress={() => navigator.push(routes[index + 1])}>
                      <Text {...buttonTextProps}>
                        Halo!
                      </Text>
                    </MKTouchable>
                  );
                }
              },
```

**Comment by jcollum** [comment]
@AndrewHenderson I think that's more appropriate on StackOverflow.

**Comment by AndrewHenderson** [comment]
If anyone else reads this chain, I resolved it by rebuilding my Xcode project and the linking took care of the rest. As others have mentioned, the linking doesn't take effect until you rebuild.

**Comment by jhabdas** [comment]
@AndrewHenderson **Sidebar:** Are you sure you want to be using their navigation bar when [`react-native-router-flux`](https://github.com/aksonov/react-native-router-flux/) exists?

**Comment by AndrewHenderson** [comment]
@jhabdas I'll check that project out. I'm new to React Native and React. It's been a lot of discovery.

**Comment by AndrewHenderson** [comment]
@jhabdas Do you know if that works well with Redux? I found `react-native-router-redux`, however the repo appears inactive.

**Comment by jhabdas** [comment]
Works great with Redux. And made to do so. Hope this helps you @AndrewHenderson https://habd.as/awesome-react-boilerplates
