### ISSUE TITLE
placeholder color style

### ISSUE THREAD

**Issue by ssavajols** [xinthink/react-native-material-kit#88]
Hi all,

How can we set the placeholder color style ? 

TintColor do not affect the placeholder. v 0.2.5

**Comment by ssavajols** [comment]
Use placeholderTextColor props like textInput component.

**Comment by jimmyhmiller** [comment]
Are the docs going to be updated to reflect this? http://www.xinthink.com/react-native-material-kit/docs/lib/mdl/Textfield.html#props doesn't mention it at all.
