### ISSUE TITLE
Getting started - Android - Extending ReactActivity

### ISSUE THREAD

**Issue by jyskit** [xinthink/react-native-material-kit#93]
The Getting started section for Android - item 4 should probably be changed to something like this - if your MainActivity inherits from ReactActivity:

import com.github.xinthink.rnmk.ReactMaterialKitPackage;
...
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(), new ReactMaterialKitPackage());
    }

**Comment by graywolf336** [comment]
Feel free to submit a pull request to change that yourself! :+1:

**Comment by xinthink** [comment]
Thanks for reporting. I'll update the example code later.
The lib may be used it in a pure RN project or a hybrid one, it's very hard to meet everyone's need. I think  it should be put in the guide, that the way linking the lib is up to you, depends on the architecture of the project.
