### ISSUE TITLE
Project not configured to use Airbnb linter

### ISSUE THREAD

**Issue by awaidmann** [xinthink/react-native-material-kit#95]
The contribution guide mentions using these styling guides:
* [Airbnb JavaScript Style Guide]
* [Airbnb React/JSX Style Guide]

However, the [.eslintrc] file is not configured to use their configurations. It seems that only rules set are these:
```jsx
  "rules": {
    "comma-dangle": [1, "always-multiline"],
    "no-underscore-dangle": 0,
    "quotes": [1, "single", "avoid-escape"]
  },
```

The linter config file needs to extend the Airbnb configuration file as shown:
```jsx
{
  "extends": "airbnb",
  "parser": "babel-eslint",          // https://github.com/babel/babel-eslint
  "plugins": [
    "react"                          // https://github.com/yannickcr/eslint-plugin-react
  ],
```

The linter extension can be found on [npm]. Install instructions can be found there as well.

I'm using Atom as my editor and below is a screen shot of the linter before and after the Airbnb configurations were enabled.

<img width="566" alt="screen shot 2016-02-02 at 1 16 19 pm" src="https://cloud.githubusercontent.com/assets/16245422/12764533/394310d6-c9af-11e5-8273-e40a6eae71c8.png">
<img width="654" alt="screen shot 2016-02-02 at 1 15 39 pm" src="https://cloud.githubusercontent.com/assets/16245422/12764537/412bc928-c9af-11e5-857a-c6fa21e3c53e.png">

If not including the Airbnb configurations is intentional feel free to close out this issue.

[Airbnb JavaScript Style Guide]: https://github.com/airbnb/javascript
[Airbnb React/JSX Style Guide]: https://github.com/airbnb/javascript/tree/master/react
[.eslintrc]: https://github.com/xinthink/react-native-material-kit/blob/master/.eslintrc
[npm]: https://www.npmjs.com/package/eslint-config-airbnb

**Comment by xinthink** [comment]
Thank you, I'll make the modification
