### ISSUE TITLE
Set Slider value with component prop

### ISSUE THREAD

**Issue by dmwallace** [xinthink/react-native-material-kit#96]
It seems like the way to change the slider's value programatically is to set the .value property on this.refs["sliderRef"].  

This makes it very difficult to initialize the slider value based on a parent prop on first render.

Just wondering why it was implemented this way?

**Comment by xinthink** [comment]
Props of react component are intent to be immutable, so I thought maybe a setter would be more useful.
Yes, I can add a `value` prop in the next release.

**Comment by gre** [comment]
+1 for a value prop

**Comment by dionysiusmarquis** [comment]
+1

**Comment by marcoreat** [comment]
+1
